export enum SUPPORTED_LANGUAGES {
  DE = 'de',
  EN = 'en'
}

interface IAppConfig {
  DEFAULT_LANG: SUPPORTED_LANGUAGES
  SUPPORTED_LANGUAGE_LIST: string[]
}

export const APP_CONFIG: IAppConfig = {
  DEFAULT_LANG: SUPPORTED_LANGUAGES.DE,
  SUPPORTED_LANGUAGE_LIST: Object.values(SUPPORTED_LANGUAGES)
}

export enum APP_ROLES {
  LANDLORD = 1,
  ADMIN = 2,
  USER = 3,
  PROPERTY_MANAGER = 4
}

export enum FILE_TYPE {
  COVER = 'cover',
  PLAN = 'plan',
  CUSTOM = 'custom',
  DOC = 'doc',
  IMAGE = 'image',
  EXTERNAL = 'external',
  GALLERY = 'gallery',
  UNASSIGNED = 'unassigned',
  ENERGY_CERTIFICATE = 'energy_certificate',
  INTERNAL = 'internal'
}

export enum ENVIRONMENT {
  TEST = 'test',
  DEV = 'development',
  PROD = 'production'
}

export enum USER_ACTIVATION_STATUS {
  NOT_ACTIVATED = 1,
  ACTIVATED = 2,
  DEACTIVATED = 3,
}

export enum PUBLISH_STATUS {
  INIT = 0,
  BY_LANDLORD = 1,
  APPROVED_BY_ADMIN = 2,
  DECLINED_BY_ADMIN = 3,
}

export enum DEVICE_TYPE {
  ANDROID = 'android',
  IOS = 'ios',
}

export enum PROPERTY_TYPE {
  APARTMENT = 1,
  ROOM = 2,
  HOUSE = 3,
  SITE = 4,
  OFFICE = 5,
  SHORT_TERM = 6,
}

export enum APARTMENT_TYPE {
  NO_INFORMATION = 0,
  FLAT = 1,
  GROUND = 2,
  ROOF = 3,
  MAISONETTE = 4,
  LOFT = 5,
  SOCIAL = 6,
  SOUTERRAIN = 7,
  PENTHOUSE = 8,
  TERRACES = 9,
  // ETAGE = 10, REMAPPED to FLAT
  HOLIDAY = 10,
  GALLERY = 11,
  // RAW_ATTIC = 12, REMAPPED to ATTIC
  ATTIC = 12,
}

export enum HEATING_TYPE {
  NO = 0,
  CENTRAL = 1,
  FLOOR = 2,
  REMOTE = 3,
  OVEN = 4,
  UNDERFLOOR = 5,
  MISC = 6,
}

export enum FIRING_TYPE {
  OEL = 1,
  GAS = 2,
  ELECTRIC = 3,
  ALTERNATIVE = 4,
  SOLAR = 5,
  GROUND_HEAT = 6,
  AIRWP = 7,
  REMOTE = 8,
  BLOCK = 9,
  WATER_ELECTRIC = 10,
  PELLET = 11,
  COAL = 12,
  WOOD = 13,
  LIQUID_GAS = 14,
}

export enum PARKING_SPACE_TYPE {
  NO_PARKING = 0,
  UNDERGROUND = 1,
  CARPORT = 2,
  OUTDOOR = 3,
  CAR_PARK = 4,
  DUPLEX = 5,
  GARAGE = 6,
}

export enum OPTIONS_TYPE {
  BUILD = 'build',
  APT = 'apt',
  OUT = 'out',
  BAD = 'bad',
  KITCHEN = 'kitchen',
  ROOM = 'room'
}

export enum BUILDING_STATUS {
  FIRST_TIME_OCCUPIED = 1,
  PART_COMPLETE_RENOVATION_NEED = 2,
  NEW = 3,
  EXISTING = 4,
  PART_FULLY_RENOVATED = 5,
  PARTLY_REFURISHED = 6,
  IN_NEED_OF_RENOVATION = 7,
  READY_TO_BE_BUILT = 8,
  BY_AGREEMENT = 9,
  MODERNIZED = 10,
  CLEANED = 11,
  ROUGH_BUILDING = 12,
  DEVELOPED = 13,
  ABRISSOBJEKT = 14,
  PROJECTED = 15,
  FULLY_REFURBISHED = 16,
}

export enum ESTATE_SYNC_LISTING_STATUS {
  PUBLISHED = 1,
  DELETED = 2,
  INITIALIZED = 3,
  POSTED = 5,
  ERROR_FOUND = 6,
  SCHEDULED_FOR_DELETE = 7,
}

export enum PETS {
  NO = 1,
  SMALL = 2,
  BIG = 3,
}

export enum CURRENCY {
  EUR = 'EUR',
  USD = 'USD',
  UAH = 'UAH',
}

export enum SALUTATION_LABEL {
  MR = 'landlord.profile.user_details.salut.mr.message',
  MS = 'landlord.profile.user_details.salut.ms.message',
  SIR_OR_MADAM = 'landlord.profile.user_details.salut.sir_madam.message',
  NEUTRAL = 'landlord.profile.user_details.salut.not_def.message',
}

export enum USER_STATUS {
  ACTIVE = 1,
  DELETE = 2,
  NEED_VERIFY = 3,
  EMAIL_VERIFY = 4,
  DRAFT = 5,
  EXPIRE = 6,
  OFFLINE_ACTIVE = 7,
}

type ObjectValues<T> = T[keyof T]
export type EstateSyncCredentialType = ObjectValues<typeof ESTATE_SYNC_CREDENTIAL_TYPE>
export const ESTATE_SYNC_CREDENTIAL_TYPE = {
  BREEZE: 'breeze',
  USER: 'user'
} as const

const constants = {
  DOMAIN: 'breeze4me.de',

  TEST_ENVIRONMENT: ENVIRONMENT.TEST,
  DEV_ENVIRONMENT: ENVIRONMENT.DEV,
  PROD_ENVIRONMENT: ENVIRONMENT.PROD,

  USER_ACTIVATION_STATUS_NOT_ACTIVATED: USER_ACTIVATION_STATUS.NOT_ACTIVATED,
  USER_ACTIVATION_STATUS_ACTIVATED: USER_ACTIVATION_STATUS.ACTIVATED,
  USER_ACTIVATION_STATUS_DEACTIVATED: USER_ACTIVATION_STATUS.DEACTIVATED,

  ERROR_AGREEMENT_CONFIRM: 10020,
  ERROR_TERMS_CONFIRM: 10030,
  ERROR_USER_NOT_VERIFIED_LOGIN: 10040,
  ERROR_WRONG_HOUSEHOLD_INVITATION_DATA: 10050,
  ERROR_BUDDY_EXISTS: 10110,
  ERROR_USER_INCOME_EXPIRE: 10140,
  ERROR_LANDLORD_DOES_NOT_OWN_THIS_ESTATE: 10150,
  ERROR_VIEW_INVITE_NOT_EXISTING: 10160,
  ERROR_PROSPECT_HAS_ALREADY_REGISTERED: 10180,
  ERROR_CHANGE_EMAIL_PASSWORD_NOT_MATCH: 10210,
  ERROR_ESTATE_NOT_FOUND_BY_HASH: 10220,
  ERROR_OUTSIDE_TENANT_INVITATION_EXPIRED: 10300,
  ERROR_OUTSIDE_TENANT_INVITATION_INVALID: 10301,
  ERROR_OUTSIDE_TENANT_INVITATION_ALREADY_USED: 10302,
  ERROR_OUTSIDE_LANDLORD_INVITATION_INVALID: 10303,

  LANG_EN: SUPPORTED_LANGUAGES.EN,
  LANG_DE: SUPPORTED_LANGUAGES.DE,
  AVAILABLE_LANGUAGES: APP_CONFIG.SUPPORTED_LANGUAGE_LIST,
  DEFAULT_LANG: APP_CONFIG.DEFAULT_LANG,

  FILE_TYPE_COVER: FILE_TYPE.COVER,
  FILE_TYPE_PLAN: FILE_TYPE.PLAN,
  FILE_TYPE_CUSTOM: FILE_TYPE.CUSTOM,
  FILE_TYPE_DOC: FILE_TYPE.DOC,
  FILE_TYPE_IMAGE: FILE_TYPE.IMAGE,
  FILE_TYPE_EXTERNAL: FILE_TYPE.EXTERNAL,
  FILE_TYPE_GALLERY: FILE_TYPE.GALLERY,
  FILE_TYPE_UNASSIGNED: FILE_TYPE.UNASSIGNED,
  FILE_TYPE_ENERGY_CERTIFICATE: FILE_TYPE.ENERGY_CERTIFICATE,

  MAX_MINOR_COUNT: 15,

  MAX_SEARCH_ITEMS: 10000,

  GALLERY_INSIDE_VIEW_TYPE: 'inside',
  GALLERY_DOCUMENT_VIEW_TYPE: 'document',

  DOCUMENT_VIEW_ENERGY_TYPE: 'energy',

  MEMBER_FILE_TYPE_RENT: 'rent_proof',
  MEMBER_FILE_TYPE_DEBT: 'debt_proof',
  MEMBER_FILE_TYPE_INCOME: 'income_proof',
  MEMBER_FILE_TYPE_PASSPORT: 'passport',

  MEMBER_FILE_TYPE_EXTRA_RENT: 'extra_rent_proof',
  MEMBER_FILE_TYPE_EXTRA_DEBT: 'extra_debt_proof',
  MEMBER_FILE_TYPE_EXTRA_PASSPORT: 'extra_passport',

  MEMBER_FILE_RENT_ARREARS_DOC: 'rent_arrears_doc',
  MEMBER_FILE_EXTRA_RENT_ARREARS_DOC: 'extra_rent_arrears_doc',
  MEMBER_FILE_DEBT_PROOFS_DOC: 'debt_proof',
  MEMBER_FILE_EXTRA_DEBT_PROOFS_DOC: 'extra_debt_proof',
  MEMBER_FILE_PASSPORT_DOC: 'passport',
  MEMBER_FILE_EXTRA_PASSPORT_DOC: 'extra_passport',

  DEVICE_TYPE_ANDROID: DEVICE_TYPE.ANDROID,
  DEVICE_TYPE_IOS: DEVICE_TYPE.IOS,

  CURRENCY_EUR: CURRENCY.EUR,
  CURRENCY_USD: CURRENCY.USD,
  CURRENCY_UAH: CURRENCY.UAH,

  STATUS_ACTIVE: USER_STATUS.ACTIVE,
  STATUS_DELETE: USER_STATUS.DELETE,
  STATUS_NEED_VERIFY: USER_STATUS.NEED_VERIFY,
  STATUS_EMAIL_VERIFY: USER_STATUS.EMAIL_VERIFY,
  STATUS_DRAFT: USER_STATUS.DRAFT,
  STATUS_EXPIRE: USER_STATUS.EXPIRE,
  STATUS_OFFLINE_ACTIVE: USER_STATUS.OFFLINE_ACTIVE,

  IS_PRIVATE: 1,
  IS_PUBLIC: 2,

  ROLE_LANDLORD: APP_ROLES.LANDLORD,
  ROLE_ADMIN: APP_ROLES.ADMIN,
  ROLE_USER: APP_ROLES.USER,
  ROLE_PROPERTY_MANAGER: APP_ROLES.PROPERTY_MANAGER,

  GENDER_MALE: 1,
  GENDER_FEMALE: 2,
  GENDER_NEUTRAL: 4,
  GENDER_ANY: 3,

  SALUTATION_MR_LABEL: SALUTATION_LABEL.MR,
  SALUTATION_MS_LABEL: SALUTATION_LABEL.MS,
  SALUTATION_SIR_OR_MADAM_LABEL: SALUTATION_LABEL.SIR_OR_MADAM,
  SALUTATION_NEUTRAL_LABEL: SALUTATION_LABEL.NEUTRAL,

  OCCUPATION_TYPE_OCCUPIED_OWN: 1,
  OCCUPATION_TYPE_OCCUPIED_TENANT: 2,
  OCCUPATION_TYPE_WRITE_OFF: 3,
  OCCUPATION_TYPE_VACANCY: 4,
  OCCUPATION_TYPE_NOT_RENT: 5,
  OCCUPATION_TYPE_NOT_OCCUPIED: 6,

  USE_TYPE_RESIDENTIAL: 1,
  USE_TYPE_COMMERCIAL: 2,
  USE_TYPE_CONSTRUCT: 3,
  USE_TYPE_WAZ: 4,
  USE_TYPE_PLANT: 5,
  USE_TYPE_OTHER: 6,

  GLOBAL_CACHE_KEY: 'GLOBAL_OPTIONS',
  GLOBAL_CACHE_OPTION: 'apt_options',
  GLOBAL_CACHE_CITY: 'apt_cities',

  OWNERSHIP_TYPE_FREEHOLDER: 1,
  OWNERSHIP_TYPE_DIRECT_PROPERTY: 2,
  OWNERSHIP_TYPE_LEASEHOLD: 3,
  OWNERSHIP_TYPE_OTHER: 4,

  MARKETING_TYPE_PURCHASE: 1,
  MARKETING_TYPE_RENT_LEASE: 2,
  MARKETING_TYPE_LEASEHOLD: 3,
  MARKETING_TYPE_LEASING: 4,

  // property_type
  PROPERTY_TYPE_APARTMENT: PROPERTY_TYPE.APARTMENT,
  PROPERTY_TYPE_ROOM: PROPERTY_TYPE.ROOM,
  PROPERTY_TYPE_HOUSE: PROPERTY_TYPE.HOUSE,
  PROPERTY_TYPE_SITE: PROPERTY_TYPE.SITE,
  PROPERTY_TYPE_OFFICE: PROPERTY_TYPE.OFFICE,
  PROPERTY_TYPE_SHORT_TERM: PROPERTY_TYPE.SHORT_TERM,

  ENERGY_TYPE_LOW_ENERGY: 1,
  ENERGY_TYPE_PASSIVE_HOUSE: 2,
  ENERGY_TYPE_NEW_BUILDING_STANDARD: 3,
  ENERGY_TYPE_KFW40: 4,
  ENERGY_TYPE_KFW60: 5,
  ENERGY_TYPE_KFW55: 6,
  ENERGY_TYPE_KFW70: 7,
  ENERGY_TYPE_MINERGIE_CONSTRUCTION: 8,
  ENERGY_TYPE_MINERGIE_CERTIFIED: 9,

  BUILDING_STATUS_FIRST_TIME_OCCUPIED: BUILDING_STATUS.FIRST_TIME_OCCUPIED,
  BUILDING_STATUS_PART_COMPLETE_RENOVATION_NEED: BUILDING_STATUS.PART_COMPLETE_RENOVATION_NEED,
  BUILDING_STATUS_NEW: BUILDING_STATUS.NEW,
  BUILDING_STATUS_EXISTING: BUILDING_STATUS.EXISTING,
  BUILDING_STATUS_PART_FULLY_RENOVATED: BUILDING_STATUS.PART_FULLY_RENOVATED,
  BUILDING_STATUS_PARTLY_REFURISHED: BUILDING_STATUS.PARTLY_REFURISHED,
  BUILDING_STATUS_IN_NEED_OF_RENOVATION: BUILDING_STATUS.IN_NEED_OF_RENOVATION,
  BUILDING_STATUS_READY_TO_BE_BUILT: BUILDING_STATUS.READY_TO_BE_BUILT,
  BUILDING_STATUS_BY_AGREEMENT: BUILDING_STATUS.BY_AGREEMENT,
  BUILDING_STATUS_MODERNIZED: BUILDING_STATUS.MODERNIZED,
  BUILDING_STATUS_CLEANED: BUILDING_STATUS.CLEANED,
  BUILDING_STATUS_ROUGH_BUILDING: BUILDING_STATUS.ROUGH_BUILDING,
  BUILDING_STATUS_DEVELOPED: BUILDING_STATUS.DEVELOPED,
  BUILDING_STATUS_ABRISSOBJEKT: BUILDING_STATUS.ABRISSOBJEKT,
  BUILDING_STATUS_PROJECTED: BUILDING_STATUS.PROJECTED,
  BUILDING_STATUS_FULLY_REFURBISHED: BUILDING_STATUS.FULLY_REFURBISHED,

  ROOM_TYPE_GUEST_ROOM: 1,
  ROOM_TYPE_BATH: 2,
  ROOM_TYPE_BEDROOM: 3,
  ROOM_TYPE_KITCHEN: 4,
  ROOM_TYPE_CORRIDOR: 5,
  ROOM_TYPE_OFFICE: 6,
  ROOM_TYPE_PANTRY: 7,
  ROOM_TYPE_CHILDRENS_ROOM: 8,
  ROOM_TYPE_BALCONY: 9,
  ROOM_TYPE_WC: 10,
  ROOM_TYPE_OTHER_SPACE: 11,
  ROOM_TYPE_CHECKROOM: 12,
  ROOM_TYPE_DINING_ROOM: 13,
  ROOM_TYPE_ENTRANCE_HALL: 14,
  ROOM_TYPE_GYM: 15,
  ROOM_TYPE_IRONING_ROOM: 16,
  ROOM_TYPE_LIVING_ROOM: 17,
  ROOM_TYPE_LOBBY: 18,
  ROOM_TYPE_MASSAGE_ROOM: 19,
  ROOM_TYPE_STORAGE_ROOM: 20,
  ROOM_TYPE_PLACE_FOR_GAMES: 21,
  ROOM_TYPE_SAUNA: 22,
  ROOM_TYPE_SHOWER: 23,
  ROOM_TYPE_STAFF_ROOM: 24,
  ROOM_TYPE_SWIMMING_POOL: 25,
  ROOM_TYPE_TECHNICAL_ROOM: 26,
  ROOM_TYPE_TERRACE: 27,
  ROOM_TYPE_WASHING_ROOM: 28,
  ROOM_TYPE_EXTERNAL_CORRIDOR: 29,
  ROOM_TYPE_STAIRS: 30,
  ROOM_TYPE_PROPERTY_ENTRANCE: 31,
  ROOM_TYPE_GARDEN: 32,
  ROOM_TYPE_LOGGIA: 33,

  // apartment type
  APARTMENT_TYPE_NO_INFORMATION: APARTMENT_TYPE.NO_INFORMATION,
  APARTMENT_TYPE_FLAT: APARTMENT_TYPE.FLAT,
  APARTMENT_TYPE_GROUND: APARTMENT_TYPE.GROUND,
  APARTMENT_TYPE_ROOF: APARTMENT_TYPE.ROOF,
  APARTMENT_TYPE_MAISONETTE: APARTMENT_TYPE.MAISONETTE,
  APARTMENT_TYPE_LOFT: APARTMENT_TYPE.LOFT,
  APARTMENT_TYPE_SOCIAL: APARTMENT_TYPE.SOCIAL,
  APARTMENT_TYPE_SOUTERRAIN: APARTMENT_TYPE.SOUTERRAIN,
  APARTMENT_TYPE_PENTHOUSE: APARTMENT_TYPE.PENTHOUSE,
  APARTMENT_TYPE_TERRACES: APARTMENT_TYPE.TERRACES,
  // APARTMENT_TYPE_ETAGE: 10, REMAPPED to APARTMENT_TYPE.FLAT
  APARTMENT_TYPE_HOLIDAY: APARTMENT_TYPE.HOLIDAY,
  APARTMENT_TYPE_GALLERY: APARTMENT_TYPE.GALLERY,
  // APARTMENT_TYPE_RAW_ATTIC: 12, REMAPPED to APARTMENT_TYPE.ATTIC
  APARTMENT_TYPE_ATTIC: APARTMENT_TYPE.ATTIC,

  // Building type
  HOUSE_TYPE_MULTIFAMILY_HOUSE: 1,
  HOUSE_TYPE_HIGH_RISE: 2,
  HOUSE_TYPE_SERIES: 3,
  HOUSE_TYPE_SEMIDETACHED_HOUSE: 4,
  HOUSE_TYPE_2FAMILY_HOUSE: 5,
  HOUSE_TYPE_DETACHED_HOUSE: 6,
  HOUSE_TYPE_COUNTRY: 7,
  HOUSE_TYPE_BUNGALOW: 8,
  HOUSE_TYPE_VILLA: 9,
  HOUSE_TYPE_GARDENHOUSE: 10,

  PARKING_SPACE_TYPE_NO_PARKING: PARKING_SPACE_TYPE.NO_PARKING,
  PARKING_SPACE_TYPE_UNDERGROUND: PARKING_SPACE_TYPE.UNDERGROUND,
  PARKING_SPACE_TYPE_CARPORT: PARKING_SPACE_TYPE.CARPORT,
  PARKING_SPACE_TYPE_OUTDOOR: PARKING_SPACE_TYPE.OUTDOOR,
  PARKING_SPACE_TYPE_CAR_PARK: PARKING_SPACE_TYPE.CAR_PARK,
  PARKING_SPACE_TYPE_DUPLEX: PARKING_SPACE_TYPE.DUPLEX,
  PARKING_SPACE_TYPE_GARAGE: PARKING_SPACE_TYPE.GARAGE,

  FIRING_OEL: FIRING_TYPE.OEL,
  FIRING_GAS: FIRING_TYPE.GAS,
  FIRING_ELECTRIC: FIRING_TYPE.ELECTRIC,
  FIRING_ALTERNATIVE: FIRING_TYPE.ALTERNATIVE,
  FIRING_SOLAR: FIRING_TYPE.SOLAR,
  FIRING_GROUND_HEAT: FIRING_TYPE.GROUND_HEAT,
  FIRING_AIRWP: FIRING_TYPE.AIRWP,
  FIRING_REMOTE: FIRING_TYPE.REMOTE,
  FIRING_BLOCK: FIRING_TYPE.BLOCK,
  FIRING_WATER_ELECTRIC: FIRING_TYPE.WATER_ELECTRIC,
  FIRING_PELLET: FIRING_TYPE.PELLET,
  FIRING_COAL: FIRING_TYPE.COAL,
  FIRING_WOOD: FIRING_TYPE.COAL,
  FIRING_LIQUID_GAS: FIRING_TYPE.LIQUID_GAS,

  HEATING_TYPE_NO: HEATING_TYPE.NO,
  HEATING_TYPE_CENTRAL: HEATING_TYPE.CENTRAL,
  HEATING_TYPE_FLOOR: HEATING_TYPE.FLOOR,
  HEATING_TYPE_REMOTE: HEATING_TYPE.REMOTE,
  HEATING_TYPE_OVEN: HEATING_TYPE.OVEN,
  HEATING_TYPE_UNDERFLOOR: HEATING_TYPE.UNDERFLOOR,
  HEATING_TYPE_MISC: HEATING_TYPE.MISC,

  EQUIPMENT_STANDARD_SIMPLE: 1,
  EQUIPMENT_STANDARD_NORMAL: 2,
  EQUIPMENT_STANDARD_ENHANCED: 3,

  ATTACHMENT_TITLE_PICTURE: 1,
  ATTACHMENT_INTERIOR_VIEWS: 2,
  ATTACHMENT_EXTERIOR_VIEWS: 3,
  ATTACHMENT_FLOOR_PLAN: 4,
  ATTACHMENT_MAPS_SITE_PLAN: 5,
  ATTACHMENT_PROVIDER_LOGO: 6,
  ATTACHMENT_PICTURE: 7,
  ATTACHMENT_DOCUMENTS: 8,
  ATTACHMENT_LINKS: 9,
  ATTACHMENT_PANORAMA: 10,
  ATTACHMENT_QRCODE: 11,
  ATTACHMENT_FILM: 12,
  ATTACHMENT_FILMLINK: 13,
  ATTACHMENT_EPASS_SCALE: 14,
  ATTACHMENT_ANBOBJURL: 5,

  GROUND_TILES: 1,
  GROUND_STONE: 2,
  GROUND_CARPET: 3,
  GROUND_PARQUET: 4,
  GROUND_FINISHED_PARQUET: 5,
  GROUND_LAMINATE: 6,
  GROUND_DIELEN: 7,
  GROUND_PLASTIC: 8,
  GROUND_ESTRICH: 9,
  GROUND_DOUBLE_FLOOR: 10,
  GROUND_LINOLEUM: 11,
  GROUND_MARMOR: 12,
  GROUND_TERRAKOTTA: 13,
  GROUND_GRANITE: 14,

  BATH_TUB: 1,
  BATH_WINDOW: 2,
  BATH_BIDET: 3,
  BATH_URINAL: 4,
  BATH_SHOWER: 5,

  KITCHEN_OPEN: 1,
  KITCHEN_PANTRY: 2,
  KITCHEN_BUILTIN: 3,

  EQUIPMENT_STACK: 1,
  EQUIPMENT_AIR_CONDITIONED: 2,
  EQUIPMENT_ELEVATOR: 3,
  EQUIPMENT_GARDEN_USE: 4,
  EQUIPMENT_WHEELCHAIR_ACCESSIBLE: 5,
  EQUIPMENT_BIKE_ROOM: 6,
  EQUIPMENT_GUEST_WC: 7,
  EQUIPMENT_WG_SUITABLE: 8,

  PETS_NO: 1,
  PETS_SMALL: 2,
  PETS_ANY: null,
  PETS_BIG: 3,

  KIDS_NO_KIDS: 1,
  KIDS_TO_5: 2,
  KIDS_UP_5: 3,

  SOURCE_TYPE_BUDDY: 1,
  SOURCE_TYPE_MATCHED: 2,

  BUILDING_AGE_NEW: 1,
  BUILDING_AGE_OLD: 2,

  ADULT_AGE_25: 1,
  ADULT_AGE_25_59: 2,
  ADULT_AGE_60: 3,

  LANDLORD_SIZE_SMALL: 1,
  LANDLORD_SIZE_MID: 2,
  LANDLORD_SIZE_LARGE: 3,

  OPTIONS_TYPE_BUILD: OPTIONS_TYPE.BUILD,
  OPTIONS_TYPE_APT: OPTIONS_TYPE.APT,
  OPTIONS_TYPE_OUT: OPTIONS_TYPE.OUT,
  OPTIONS_TYPE_BAD: OPTIONS_TYPE.BAD,
  OPTIONS_TYPE_KITCHEN: OPTIONS_TYPE.KITCHEN,
  OPTIONS_TYPE_ROOM: OPTIONS_TYPE.ROOM,

  HIRING_TYPE_FULL_TIME: 'full',
  HIRING_TYPE_PART_TIME: 'part',

  TRANSPORT_TYPE_CAR: 'car',
  TRANSPORT_TYPE_WALK: 'walk',
  TRANSPORT_TYPE_SOCIAL: 'soc',

  POINT_TYPE_ZONE: 'zone',
  POINT_TYPE_POI: 'poi',

  INCOME_TYPE_EMPLOYEE: 'employee',
  INCOME_TYPE_WORKER: 'worker',
  INCOME_TYPE_UNEMPLOYED: 'unemployed',
  INCOME_TYPE_CIVIL_SERVANT: 'civil_servant',
  INCOME_TYPE_FREELANCER: 'freelancer',
  INCOME_TYPE_HOUSE_WORK: 'housewife_husband',
  INCOME_TYPE_PENSIONER: 'pensioner',
  INCOME_TYPE_SELF_EMPLOYED: 'self',
  INCOME_TYPE_TRAINEE: 'trainee',
  INCOME_TYPE_OTHER_BENEFIT: 'other_benefit',
  INCOME_TYPE_CHILD_BENEFIT: 'child_benefit',

  FAMILY_STATUS_SINGLE: 1,
  FAMILY_STATUS_WITH_CHILD: 3,
  FAMILY_STATUS_NO_CHILD: 2,

  NO_MATCH_STATUS: -1,
  MATCH_STATUS_NEW: 1,
  MATCH_STATUS_KNOCK: 2,
  MATCH_STATUS_INVITE: 3,
  MATCH_STATUS_VISIT: 4,
  MATCH_STATUS_SHARE: 5,
  MATCH_STATUS_TOP: 6,
  MATCH_STATUS_COMMIT: 7,
  MATCH_STATUS_FINISH: 8,

  ACTIVE_VISUALS_BY_AREA: 1,
  ACTIVE_VISUALS_BY_BULK_UPLOAD: 2,

  NO_LANDLORD_REQUEST_TENANT_SHARE_PROFILE: 0,
  LANDLORD_REQUEST_TENANT_SHARE_PROFILE_REQUESTED: 1,
  LANDLORD_REQUEST_TENANT_SHARE_PROFILE_SHARED: 2,
  LANDLORD_REQUEST_TENANT_SHARE_PROFILE_DECLINED: 3,

  TENANT_EMAIL_INVITE: 1,
  TENANT_SMS_INVITE: 2,

  COMPANY_TYPE_PRIVATE: 'private',
  COMPANY_TYPE_PROPERTY_MANAGER: 'propMan',
  COMPANY_TYPE_PRIVATE_HOUSING: 'prHost',
  COMPANY_TYPE_MUNICIPAL_HOUSING: 'numHost',
  COMPANY_TYPE_HOUSING_COOPERATIVE: 'hostCoop',
  COMPANY_TYPE_LISTED_HOUSING: 'listHost',
  COMPANY_TYPE_BROKER: 'broker',

  COMPANY_SIZE_SMALL: 'sm',
  COMPANY_SIZE_MID: 'md',
  COMPANY_SIZE_LARGE: 'lg',

  // Tabs matches list
  TENANT_TABS_BUDDY: 'buddy',
  TENANT_TABS_LIKE: 'like',
  TENANT_TABS_DISLIKE: 'dislike',
  TENANT_TABS_KNOCK: 'knock',
  TENANT_TABS_INVITE: 'invite',
  TENANT_TABS_SHARE: 'share',
  TENANT_TABS_TOP: 'top',
  TENANT_TABS_COMMIT: 'commit',

  LANDLORD_TABS_KNOCK: 'knock',
  LANDLORD_TABS_BUDDY: 'buddy',
  LANDLORD_TABS_INVITE: 'invite',
  LANDLORD_TABS_VISIT: 'visit',
  LANDLORD_TABS_TOP: 'top',
  LANDLORD_TABS_COMMIT: 'commit',

  NO_VISIBLE_BEFORE_TENANT: 0,
  VISIBLE_BEFORE_TENANT: 1,

  DATE_FORMAT: 'YYYY-MM-DD HH:mm:ss',
  GERMAN_DATE_TIME_FORMAT: 'DD.MM.YYYY, HH:mm',
  GERMAN_DATE_FORMAT: 'DD.MM.YYYY',
  DAY_FORMAT: 'YYYY-MM-DD',
  ISO_DATE_FORMAT: 'YYYY-MM-DD"T"HH24:MI:SS"Z"', // ISO 8601

  MAXIMUM_EXPIRE_PERIOD: 3 * 30, // 90 days

  AMENITIES_OPTIONS: [
    'elevator',
    'cellar',
    'parking_space',
    'apt_balcony',
    'furnished',
    'bathtub',
    'fitted_kitchen'
  ],

  ESTATE_NOTIFICATION_FIELDS: [
    'id',
    'address',
    'cover',
    'rooms_number',
    'area',
    'floor',
    'number_floors'
  ],
  PROSPECT_DEACTIVATION_STAGE_FIRST_WARNING: 1,
  PROSPECT_DEACTIVATION_STAGE_SECOND_WARNING: 2,
  PROSPECT_DEACTIVATION_STAGE_FINAL: 3,
  REMIND_PROSPECT_TO_ACTIVATE_IN_ONE_DAY: 'remindProspectToActivateInOneDay',
  REMIND_PROSPECT_TO_REACTIVATE_WHEN_DEACTIVATED_IN_SEVEN_DAYS: 'remindProspectToReactivateWhenDeactivatedInSevenDays',
  SCHEDULED_EVERY_3RD_HOUR_23RD_MINUTE_JOB: 'scheduledEvery3rdHour23rdMinuteJob',
  SCHEDULED_EVERY_37TH_MINUTE_HOURLY_JOB: 'scheduledEvery37thMinuteHourlyJob',
  SCHEDULED_EVERY_1M_JOB: 'scheduledEvery1Min',
  SCHEDULED_EVERY_5M_JOB: 'scheduledEvery5Min',
  SCHEDULED_EVERY_15MINUTE_NIGHT_JOB: 'scheduledEvery15MinuteNightJob',
  SCHEDULED_13H_DAY_JOB: 'scheduledEveryDay13H',
  SCHEDULED_9H_DAY_JOB: 'scheduledEveryDay9H',
  SCHEDULED_16H_DAY_JOB: 'scheduledEveryDayAt16H',
  SCHEDULED_FRIDAY_JOB: 'scheduledFriday',
  SCHEDULED_MONTHLY_JOB: 'scheduledStartOfEveryMonth',
  SCHEDULED_FOR_EVERY_MINUTE_ENDING_IN_3_JOB: 'scheduledForEveryMinuteEndingInThree',
  SCHEDULED_MONTHLY_AT_1ST_AND_AT_10AM: 'scheduledMonthdlyAt1stAndAt10AM',
  SCHEDULED_MONTHLY_AT_10TH_AND_AT_10AM: 'scheduledMonthlyAt10thAndAt10AM',
  SCHEDULED_MONTHLY_AT_15TH_AND_AT_10AM: 'scheduledMonthlyAt15thAndAt10AM',

  NOTICE_TYPE_LANDLORD_FILL_PROFILE: 'notification_landlord_fill_profile',
  NOTICE_TYPE_LANDLORD_NEW_PROPERTY: 'notification_landlord_new_property',
  NOTICE_TYPE_LANDLORD_TIME_FINISHED: 'notification_landlord_time_finished',
  NOTICE_TYPE_LANDLORD_CONFIRM_VISIT: 'notification_landlord_confirmed_visits',
  NOTICE_TYPE_LANDLORD_VISIT30M: 'notification_landlord_visit_starting',
  NOTICE_TYPE_LANDLORD_MATCH: 'notification_landlord_match',
  NOTICE_TYPE_LANDLORD_DECISION: 'notification_landlord_decision',
  NOTICE_TYPE_PROSPECT_NEW_MATCH: 'notification_prospect_new_match',
  NOTICE_TYPE_PROSPECT_MATCH_LEFT: 'notification_prospect_match_left',
  NOTICE_TYPE_PROSPECT_INVITE: 'notification_prospect_invite',
  NOTICE_TYPE_PROSPECT_VISIT3H: 'notification_prospect_visit_1',
  NOTICE_TYPE_PROSPECT_VISIT30M: 'notification_prospect_visit_2',
  NOTICE_TYPE_PROSPECT_VISIT48H: 'notification_prospect_visit_3',
  NOTICE_TYPE_PROSPECT_COMMIT: 'notification_prospect_commit',
  NOTICE_TYPE_PROSPECT_REJECT: 'notification_prospect_reject',
  NOTICE_TYPE_PROSPECT_NO_ACTIVITY: 'notification_prospect_no_activity',
  NOTICE_TYPE_PROSPECT_VISIT90M: 'notification_prospect_visit_90m',
  NOTICE_TYPE_LANDLORD_VISIT90M: 'notification_landlord_visit_90m',
  NOTICE_TYPE_PROSPECT_PROFILE_EXPIRE: 'notification_prospect_profile_expire',
  NOTICE_TYPE_PROSPECT_COME: 'notification_prospect_come',
  NOTICE_TYPE_CANCEL_VISIT: 'notification_cancel_visit',
  NOTICE_TYPE_CANCEL_VISIT_LANDLORD: 'notification_cancel_visit_landlord',
  NOTICE_TYPE_INVITE_TENANT_IN_TO_VISIT: 'notification_tenant_in_to_visit',
  NOTICE_TYPE_VISIT_DELAY: 'notification_visit_delay',
  NOTICE_TYPE_VISIT_DELAY_LANDLORD: 'notification_visit_delay_landlord',
  NOTICE_TYPE_ZENDESK_NOTIFY: 'notification_zendesk_notify',
  NOTICE_TYPE_USER_VERIFICATION_BY_ADMIN: 'notification_user_verification_by_admin',
  NOTICE_TYPE_ESTATE_SHOW_TIME_IS_OVER: 'notification_estate_show_time_is_over',
  NOTICE_TYPE_PROSPECT_INVITE_REMINDER: 'notification_prospect_invite_reminder',
  NOTICE_TYPE_PROSPECT_IS_NOT_INTERESTED: 'notification_prospect_is_not_interested',
  NOTICE_TYPE_LANDLORD_MOVED_PROSPECT_TO_TOP: 'notification_landlord_moved_prospect_to_top',
  NOTICE_TYPE_PROSPECT_HOUSEHOLD_INVITATION_ACCEPTED:
    'notification_prospect_household_invitation_accepted',
  NOTICE_TYPE_PROSPECT_HOUSEHOLD_DISCONNECTED: 'notification_prospect_household_disconnected',
  NOTICE_TYPE_PROSPECT_ARRIVED: 'notification_prospect_arrived',
  NOTICE_TYPE_PROSPECT_PROPERTY_DEACTIVATED: 'notification_prospect_property_deactivated',
  NOTICE_TYPE_PROSPECT_SUPER_MATCH: 'notification_prospect_super_match',
  NOTICE_TYPE_LANDLORD_SENT_TASK_MESSAGE: 'notification_type_landlord_sent_task_message',
  NOTICE_TYPE_TENANT_SENT_TASK_MESSAGE: 'notification_type_tenant_sent_task_message',
  NOTICE_TYPE_LANDLORD_DEACTIVATE_IN_TWO_DAYS: 'notification_landlord_deactivated_in_two_days',
  NOTICE_TYPE_LANDLORD_DEACTIVATE_NOW: 'notification_landlord_deactivated',
  NOTICE_TYPE_PROSPECT_INFORMED_LANDLORD_DEACTIVATED:
    'notification_prospect_informed_landlord_deactivated',
  NOTICE_TYPE_LANDLORD_FOLLOWUP_PROSPECT: 'notification_landlord_followup_prospect',
  NOTICE_TYPE_PROSPECT_FOLLOWUP_LANDLORD: 'notification_prospect_followup_landlord',
  NOTICE_TYPE_TENANT_DISCONNECTION: 'notification_tenant_disconnection',

  NOTICE_TYPE_LANDLORD_UPDATE_SLOT: 'notification_landlord_update_slot',
  NOTICE_TYPE_PROSPECT_KNOCK_PROPERTY_EXPIRED: 'notification_prospect_knock_property_expired',

  NOTICE_TYPE_PROSPECT_TASK_RESOLVED: 'notification_prospect_task_resolved',
  NOTICE_TYPE_PROSPECT_DEACTIVATED: 'notification_prospect_deactivated',

  NOTICE_TYPE_EXPIRED_SHOW_TIME: 'notification_landlord_expired_show_time',
  NOTICE_TYPE_LANDLORD_MIN_PROSPECTS_REACHED: 'notification_landlord_min_prospects_reached',
  NOTICE_TYPE_LANDLORD_GREEN_MIN_PROSPECTS_REACHED:
    'notification_landlord_green_min_prospects_reached',
  NOTICE_TYPE_PROSPECT_LIKE_EXPIRING: 'notification_prospect_like_expiring',
  NOTICE_TYPE_PROSPECT_LIKED_BUT_NOT_KNOCK: 'notification_prospect_liked_but_not_knock',
  NOTICE_TYPE_ADMIN_APPROVES_PUBLISH: 'notification_landlord_admin_approves_publish',
  NOTICE_TYPE_PROSPECT_GREEN_MATCH: 'notification_prospect_green_match',
  NOTICE_TYPE_TENANT_PROFILE_FILL_UP: 'notification_prospect_fill_up_profile',
  NOTICE_TYPE_FINAL_MATCH_REQUEST_EXPIRED: 'notification_final_match_request_expired',
  NOTICE_TYPE_PROSPECT_REACTIVATED: 'notification_prospect_reactivated',
  NOTICE_TYPE_PROSPECT_REQUEST_PROFILE: 'notification_prospect_request_profile',
  NOTICE_TYPE_PROSPECT_NEED_TO_ACTIVATE: 'notification_prospect_need_to_activate',

  NOTICE_TYPE_LANDLORD_FILL_PROFILE_ID: 2,
  NOTICE_TYPE_LANDLORD_NEW_PROPERTY_ID: 3,
  NOTICE_TYPE_LANDLORD_TIME_FINISHED_ID: 4,
  NOTICE_TYPE_LANDLORD_CONFIRM_VISIT_ID: 5,
  NOTICE_TYPE_LANDLORD_VISIT30M_ID: 7,
  NOTICE_TYPE_LANDLORD_MATCH_ID: 8,
  NOTICE_TYPE_LANDLORD_DECISION_ID: 9,
  NOTICE_TYPE_PROSPECT_NEW_MATCH_ID: 12,
  NOTICE_TYPE_PROSPECT_MATCH_LEFT_ID: 13,
  NOTICE_TYPE_PROSPECT_INVITE_ID: 14,
  NOTICE_TYPE_PROSPECT_VISIT3H_ID: 15,
  NOTICE_TYPE_PROSPECT_VISIT30M_ID: 16,
  NOTICE_TYPE_PROSPECT_COMMIT_ID: 17,
  NOTICE_TYPE_PROSPECT_NO_ACTIVITY_ID: 19,
  NOTICE_TYPE_PROSPECT_VISIT90M_ID: 20,
  NOTICE_TYPE_LANDLORD_VISIT90M_ID: 21,
  NOTICE_TYPE_PROSPECT_REJECT_ID: 22,
  NOTICE_TYPE_PROSPECT_PROFILE_EXPIRE_ID: 23,
  NOTICE_TYPE_PROSPECT_COME_ID: 24,

  NOTICE_TYPE_CANCEL_VISIT_ID: 26, // prospect sets timeslot to visit
  NOTICE_TYPE_VISIT_DELAY_ID: 27, // visit delayed
  NOTICE_TYPE_INVITE_TENANT_IN_TO_VISIT_ID: 28,
  NOTICE_TYPE_ZENDESK_NOTIFY_ID: 30,
  NOTICE_TYPE_USER_VERIFICATION_BY_ADMIN_ID: 31,
  NOTICE_TYPE_ESTATE_SHOW_TIME_IS_OVER_ID: 32,
  NOTICE_TYPE_PROSPECT_IS_NOT_INTERESTED_ID: 33,
  NOTICE_TYPE_LANDLORD_MOVED_PROSPECT_TO_TOP_ID: 34,
  NOTICE_TYPE_PROSPECT_HOUSEHOLD_INVITATION_ACCEPTED_ID: 35,
  NOTICE_TYPE_PROSPECT_HOUSEHOLD_DISCONNECTED_ID: 36,
  NOTICE_TYPE_VISIT_DELAY_LANDLORD_ID: 37, // visit delayed
  NOTICE_TYPE_CANCEL_VISIT_LANDLORD_ID: 38,
  NOTICE_TYPE_PROSPECT_ARRIVED_ID: 39,
  NOTICE_TYPE_PROSPECT_INVITE_REMINDER_ID: 40,
  NOTICE_TYPE_PROSPECT_PROPERTY_DEACTIVATED_ID: 41,
  NOTICE_TYPE_PROSPECT_SUPER_MATCH_ID: 42,
  NOTICE_TYPE_LANDLORD_SENT_TASK_MESSAGE_ID: 43,
  NOTICE_TYPE_TENANT_SENT_TASK_MESSAGE_ID: 44,
  NOTICE_TYPE_LANDLORD_DEACTIVATE_IN_TWO_DAYS_ID: 45,
  NOTICE_TYPE_LANDLORD_DEACTIVATE_NOW_ID: 46,
  NOTICE_TYPE_PROSPECT_INFORMED_LANDLORD_DEACTIVATED_ID: 47,
  NOTICE_TYPE_TENANT_DISCONNECTION_ID: 48,
  NOTICE_TYPE_LANDLORD_FOLLOWUP_PROSPECT_ID: 49,
  NOTICE_TYPE_PROSPECT_FOLLOWUP_LANDLORD_ID: 50,
  NOTICE_TYPE_LANDLORD_UPDATE_SLOT_ID: 51, // landlord updated timeslot
  NOTICE_TYPE_PROSPECT_KNOCK_PROPERTY_EXPIRED_ID: 52,
  NOTICE_TYPE_PROSPECT_TASK_RESOLVED_ID: 53,
  NOTICE_TYPE_PROSPECT_DEACTIVATED_ID: 54,
  NOTICE_TYPE_EXPIRED_SHOW_TIME_ID: 55,
  NOTICE_TYPE_LANDLORD_MIN_PROSPECTS_REACHED_ID: 56,
  NOTICE_TYPE_PROSPECT_LIKE_EXPIRING_ID: 57,
  NOTICE_TYPE_PROSPECT_LIKED_BUT_NOT_KNOCK_ID: 58,
  NOTICE_TYPE_PROSPECT_VISIT48H_ID: 59,
  NOTICE_TYPE_ADMIN_APPROVES_PUBLISH_ID: 60,
  NOTICE_TYPE_LANDLORD_GREEN_MIN_PROSPECTS_REACHED_ID: 61,
  NOTICE_TYPE_PROSPECT_GREEN_MATCH_ID: 62,
  NOTICE_TYPE_TENANT_PROFILE_FILL_UP_ID: 63,
  NOTICE_TYPE_FINAL_MATCH_REQUEST_EXPIRED_ID: 64,
  NOTICE_TYPE_PROSPECT_REACTIVATED_ID: 65,
  NOTICE_TYPE_PROSPECT_REQUEST_PROFILE_ID: 66,
  NOTICE_TYPE_PROSPECT_NEED_TO_ACTIVATE_ID: 67,

  TIMESLOT_STATUS_BOOK: 'new',
  TIMESLOT_STATUS_PRE_CONFIRM: 'pre',
  TIMESLOT_STATUS_CONFIRM: 'confirm',
  TIMESLOT_STATUS_REJECT: 'reject',
  TIMESLOT_STATUS_DELAY: 'delay',
  TIMESLOT_STATUS_COME: 'come',

  VISIT_MAX_ALLOWED_FOLLOWUPS: 3,

  MIN_TIME_SLOT: 5,

  NO_UNPAID_RENTAL: 1,
  YES_UNPAID_RENTAL: 2,
  NO_ANSWER_UNPAID_RENTAL: 3,

  NO_INSOLVENCY: 1,
  YES_INSOLVENCY: 2,
  NO_ANSWER_INSOLVENCY: 3,

  NO_CLEAN_PROCEDURE: 1,
  YES_CLEAN_PROCEDURE: 2,
  NO_ANSWER_CLEAN_PROCEDURE: 3,

  NO_INCOME_SEIZURE: 1,
  YES_INCOME_SEIZURE: 2,
  NO_ANSWER_INCOME_SEIZURE: 3,

  MONTHLY_PAYMENT: 1,
  YEARLY_PAYMENT: 2,

  BASIC_TENANT_MEMBER: 1,
  PREMIUM_TENANT_MEMBER: 2,
  BASIC_LANDLORD_MEMBER: 3,
  PREMIUM_LANDLORD_MEMBER: 4,

  BASIC_PLAN_MIN_CONNECT_COUNT: 2,
  PREMIUM_PLAN_MIN_CONNECT_COUNT: 14,

  FURNISHING_NOT_FURNISHED: 0,
  FURNISHING_PARTIALLY_FURNISHED: 1,
  FURNISHING_FULLY_FURNISHED: 2,

  PROPERTY_MANAGE_REQUEST: 1,
  PROPERTY_MANAGE_ALLOWED: 2,

  // this has to be stored in database later.
  YEARLY_DISCOUNT_RATE: 0.1,

  BUDDY_STATUS_PENDING: 1,
  BUDDY_STATUS_ACCEPTED: 2,
  BUDDY_STATUS_REMOVED: 3,

  TENANT_MATCH_FIELDS: [
    'id',
    'coord',
    'net_rent',
    'area',
    'cover',
    'country',
    'street',
    'city',
    'zip',
    'rooms_number',
    'floor',
    'number_floors',
    'house_number',
    'status',
    'match',
    'rent_per_sqm',
    'net_rent',
    'extra_costs',
    'budget',
    'updated_at',
    'share',
    'like',
    'dislike',
    'visit_status',
    'delay',
    'estate_status',
    'date',
    'visit_start_date',
    'visit_end_date',
    'email',
    'firstname',
    'secondname',
    'phone',
    'avatar',
    'sex',
    'address',
    'user_id',
    'available_start_at',
    'available_end_at',
    'vacant_date',
    'others',
    'full_address',
    'deposit',
    'energy_efficiency',
    'heating_type',
    'firing',
    'construction_year',
    'house_type',
    'apt_type',
    'options',
    'share_link',
    'publish_status',
    'publish_type',
    'stp_garage',
    'energy_proof',
    'energy_proof_original_file',
    'isoline',
    'is_new_tenant_transfer',
    'transfer_budget',
    'rent_end_at',
    'knocked_at',
    'action_at',
    'is_not_show',
    'unread_count',
    'status_at'
  ],

  SMS_VERIFY_PREFIX: 'confirm_household_account',
  SMS_MEMBER_PHONE_VERIFY_PREFIX: 'confirm_member_phone_account',
  INVITE_OUTSIDE_TENANT: 'invite_outside_breeze',
  TEMPORARY_PASSWORD_PREFIX: 'temporary_password',

  LOG_TYPE_OPEN_APP: 'open_app',
  LOG_TYPE_SIGN_UP: 'sign_up',
  LOG_TYPE_SIGN_IN: 'sign_in',
  LOG_TYPE_PUBLISHED_PROPERTY: 'published_property',
  LOG_TYPE_PROPERTIES_IMPORTED: 'properties_imported',
  LOG_TYPE_INVITED: 'invited',
  LOG_TYPE_GOT_INVITE: 'got_invite',
  LOG_TYPE_SHOWED: 'showed',
  LOG_TYPE_FINAL_MATCH_REQUEST: 'final_match_request',
  LOG_TYPE_FINAL_MATCH_APPROVAL: 'final_match_approval',
  LOG_TYPE_SIGN_IN_FIRST_TIME: 'sign_in_first_time',
  LOG_TYPE_OPEN_APP_FIRST_TIME: 'open_app_first_time',
  LOG_TYPE_SIGN_IN_HIGH_VALUE: 'sign_in_high_value',
  LOG_TYPE_SIGN_IN_LOW_VALUE: 'sign_in_low_value',
  LOG_TYPE_SIGN_IN_INACTIVE: 'sign_in_inactive',
  LOG_TYPE_ACTIVATED_PROFILE: 'activated_profile',
  LOG_TYPE_DEACTIVATED_PROFILE: 'deactivated_profile',
  LOG_TYPE_KNOCKED: 'knocked',
  LOG_TYPE_VISITED: 'visited',
  LOG_TYPE_REQUEST_PROFILE: 'request_profile',

  SIGN_IN_METHOD_GOOGLE: 'google',
  SIGN_IN_METHOD_APPLE: 'apple',
  SIGN_IN_METHOD_EMAIL: 'email',

  SIGN_UP_METHOD_GOOGLE: 'google',
  SIGN_UP_METHOD_APPLE: 'apple',
  SIGN_UP_METHOD_EMAIL: 'email',

  PLAN_FEATURE_COMMON: '',
  PLAN_FEATURE_NEW: 'New',

  VISIBLE_TO_NOBODY: 1,
  VISIBLE_TO_EVERYBODY: 2,
  VISIBLE_TO_SPECIFIC: 3,
  VISIBLE_TO_HOUSEHOLD: 4,

  LETTING_TYPE_LET: 1,
  LETTING_TYPE_VOID: 2,
  LETTING_TYPE_NA: 3,

  LETTING_STATUS_STANDARD: 1,
  LETTING_STATUS_TERMINATED: 2,
  LETTING_STATUS_VACANCY: 3,
  LETTING_STATUS_NEW_RENOVATED: 4,

  MINIMUM_SHOW_PERIOD: 5,
  ROOM_CUSTOM_AMENITIES_MAX_COUNT: 3,
  ROOM_CUSTOM_AMENITY_MAX_STRING_LENGTH: 35,
  ROOM_CUSTOM_AMENITIES_EXCEED_MAX_ERROR: 2311252,
  ROOM_CUSTOM_AMENITIES_UPDATE_REORDER_COUNT_NOT_MATCH: 5433122,

  ESTATE_CUSTOM_AMENITIES_MAX_COUNT: 3,
  ESTATE_CUSTOM_AMENITIES_EXCEED_MAX_ERROR: 23551276,
  ESTATE_AMENITIES_UPDATE_REORDER_COUNT_NOT_MATCH: 34338761,
  ESTATE_CUSTOM_AMENITY_MAX_STRING_LENGTH: 35,

  ESTATE_AMENITY_LOCATIONS: ['build', 'apt', 'out', 'room'],

  FILTER_CONSTRAINTS_MATCH_MODES: [
    'startsWith',
    'contains',
    'notContains',
    'endsWith',
    'equals',
    'notEquals',
    'gt',
    'lt',
    'gte',
    'lte'
  ],

  FILTER_CONSTRAINTS_DATE_MATCH_MODES: ['dateIs', 'dateIsNot', 'dateBefore', 'dateAfter'],
  FILTER_CONSTRAINTS_COUNT_MATCH_MODES: ['equals', 'notEquals', 'gt', 'lt', 'gte', 'lte'],

  PREDEFINED_MSG_MULTIPLE_ANSWER_MULTIPLE_CHOICE: 1,
  PREDEFINED_MSG_MULTIPLE_ANSWER_SIGNLE_CHOICE: 2,
  PREDEFINED_MSG_MULTIPLE_ANSWER_CUSTOM_CHOICE: 6,
  PREDEFINED_MSG_OPEN_ENDED: 3,
  PREDEFINED_NOT_A_QUESTION: 4,
  PREDEFINED_LAST: 5,
  PREDEFINED_MSG_OPTION_SIGNLE_CHOICE: 7,

  URGENCY_LOW: 1,
  URGENCY_NORMAL: 2,
  URGENCY_HIGH: 3,
  URGENCY_SUPER: 4,

  URGENCY_LOW_LABEL: 'Low',
  URGENCY_NORMAL_LABEL: 'Normal',
  URGENCY_HIGH_LABEL: 'High',
  URGENCY_SUPER_LABEL: 'Urgent',

  URGENCIES: [
    {
      label: 'low_notification.message',
      value: 1
    },
    {
      label: 'normal_notification.message',
      value: 2
    },
    {
      label: 'high_notification.message',
      value: 3
    },
    {
      label: 'urgent_notification.message',
      value: 4
    }
  ],
  TASK_STATUS_NEW: 1,
  TASK_STATUS_INPROGRESS: 2,
  TASK_STATUS_UNRESOLVED: 3,
  TASK_STATUS_RESOLVED: 4,

  BREEZE_BOT_USER: {
    id: 0,
    firstname: 'Breeze',
    secondname: 'Monster',
    avatar: '/img/breezeLogo.png'
  },

  TASK_STATUS_ARCHIVED: 99,
  TASK_STATUS_DRAFT: 100,
  TASK_STATUS_DELETE: 101,

  TASK_SYSTEM_TYPE: 1,
  TASK_COMMON_TYPE: 2,

  TASK_ORDER_BY_URGENCY: 'urgency',
  TASK_ORDER_BY_UNREAD: 'unread',

  TASK_STATUS_NEW_LABEL: 'New',
  TASK_STATUS_INPROGRESS_LABEL: 'In Progress',
  TASK_STATUS_UNRESOLVED_LABEL: 'Unresolved',
  TASK_STATUS_RESOLVED_LABEL: 'Resolved',

  ALL_BREEZE: 'All',
  CONNECTED_BREEZE_TEANT_LABEL: 'Connected',
  NOT_CONNECTED_BREEZE_TEANT_LABEL: 'Not Connected',
  PENDING_BREEZE_TEANT_LABEL: 'Pending',

  CHAT_EDIT_STATUS_UNEDITED: 'unedited',
  CHAT_EDIT_STATUS_EDITED: 'edited',
  CHAT_EDIT_STATUS_DELETED: 'deleted',

  CONNECT_PREVIOUS_MESSAGES_LIMIT_PER_PULL: 10,
  CONNECT_MESSAGE_EDITABLE_TIME_LIMIT: 3600, // seconds
  SHOW_ACTIVE_TASKS_COUNT: 3,
  ADULT_MIN_AGE: 18,

  ESTATE_FIELD_FOR_TASK: [
    'coord',
    'street',
    'area',
    'house_number',
    'country',
    'floor',
    'rooms_number',
    'number_floors',
    'city',
    'zip',
    'cover',
    'coord_raw',
    'property_id',
    'address'
  ],
  // whether we deactivate landlord at end of day of his/her deactivation day
  // or at the moment his deactivation arrives.
  DEACTIVATE_LANDLORD_AT_END_OF_DAY: false,
  // list of holidays in Germany
  // FIXME: this should come from a db table or from an external api
  GERMAN_HOLIDAYS: [
    '2022-08-15', // assumption day
    '2022-09-20', // world children day
    '2022-10-03', // reunion day
    '2022-11-01', // all saints day
    '2022-12-25', // christmas
    '2022-12-26', // seconday of christmas
    '2023-01-01', // new year's day
    '2023-01-06', // epiphany
    '2023-03-08', // Weltfrauntag
    '2023-04-07', // Good Friday
    '2023-04-09', // Easter Sunday
    '2023-04-10', // Easter Monday
    '2023-05-01', // Labor day
    '2023-05-29', // Whit Monday
    '2023-06-08', // Corpus Cristi
    '2023-08-15', // Assumption Day
    '2023-09-20', // world children's day
    '2023-10-31', // reformation day
    '2023-11-01', // all saints' day
    '2023-12-25', // christmas
    '2023-12-26', // second day of christmas
    '2024-01-01' // new year
  ],
  CHAT_TYPE_MESSAGE: 'message',
  CHAT_TYPE_BOT_MESSAGE: 'chatbot',
  CHAT_TYPE_NOTIFICATION: 'notification',
  CHAT_TYPE_LAST_READ_MARKER: 'last-read-marker',

  DEFECT_TOPICS: [
    {
      key: 'tenant.property.defect_class.Heating.message',
      text: 'Heating'
    },
    {
      key: 'tenant.property.defect_class.Window.message',
      text: 'Window'
    },
    {
      key: 'tenant.property.defect_class.Toilet.message',
      text: 'Toilet'
    },
    {
      key: 'tenant.property.defect_class.Water tap.message',
      text: 'Water tap'
    },
    {
      key: 'tenant.property.defect_class.Electricity.message',
      text: 'Electricity'
    },
    {
      key: 'tenant.property.defect_class.Door.message',
      text: 'Door'
    },
    {
      key: 'tenant.property.defect_class.Unit.message',
      text: 'Unit'
    },
    {
      key: 'tenant.property.defect_class.Bath_Shower.message',
      text: 'Bath Shower'
    },
    {
      key: 'tenant.property.defect_class.Entrance.message',
      text: 'Entrance'
    },
    {
      key: 'tenant.property.defect_class.Outside.message',
      text: 'Outside'
    },
    {
      key: 'tenant.property.defect_class.Kitchen.message',
      text: 'Kitchen'
    }
  ],

  ESTATE_FLOOR_DIRECTION_NA: 1,
  ESTATE_FLOOR_DIRECTION_LEFT: 2,
  ESTATE_FLOOR_DIRECTION_RIGHT: 3,
  ESTATE_FLOOR_DIRECTION_STRAIGHT: 4,
  ESTATE_FLOOR_DIRECTION_STRAIGHT_LEFT: 5,
  ESTATE_FLOOR_DIRECTION_STRAIGHT_RIGHT: 6,

  TENANT_INVITATION_EXPIRATION_DATE: 14, // 2 weeks

  ESTATE_VALID_ADDRESS_LABEL: 'Valid',
  ESTATE_INVALID_ADDRESS_LABEL: 'Error',
  ESTATE_ALL_ADDRESS_LABEL: 'All',

  // Date period
  TASK_RESOLVE_HISTORY_PERIOD: 3,

  CONNECT_SERVICE_INDEX: 1,
  MATCH_SERVICE_INDEX: 2,

  PASS_ONBOARDING_STEP_COMPANY: 1,
  PASS_ONBOARDING_STEP_PREFERRED_SERVICES: 2,

  INCOME_NORMAL_TYPE: 'normal',
  INCOME_EXTRA_TYPE: 'extra',

  PROSPECT_ACTOR: 'prospect',
  LANDLORD_ACTOR: 'landlord',

  LETTER_GREETING_STYLE: [0, 1, 2, 3, 4],

  INVITATION_LINK_RETRIEVAL_CODE_LENGTH: 6,
  INVITATION_LINK_RETRIEVAL_CODE_CHARACTERS: '0123456789',
  INVITATION_LINK_RETRIEVAL_MAX_TRIES_LIMIT: 10,
  INVITATION_LINK_RETRIEVAL_TRIES_RESET_TIME: 1, // in minutes
  INVITATION_LINK_RETRIEVAL_TRIES_KEY: 'userRetrieveInvitationLinkFailedTries',

  MAX_ROOM_TYPES_TO_IMPORT: 6,

  WEBSOCKET_EVENT_ESTATE_VERIED_ADDRESS: 'estate_address_verified',
  WEBSOCKET_EVENT_TASK_MESSAGE_ALL_READ: 'taskMessageRead',
  WEBSOCKET_EVENT_USER_ACTIVATE: 'landlord:activatedAccount',
  WEBSOCKET_EVENT_TENANT_CONNECTED: 'landlord:tenantConnected',
  WEBSOCKET_EVENT_MATCH_CREATED: 'tenant:createMatchCompleted',
  WEBSOCKET_EVENT_MATCH_COUNT: 'tenant:matchCount',
  WEBSOCKET_EVENT_LANDLORD_INVITED_FROM_TENANT: 'landlord:landlordInvitedFromTenant',
  WEBSOCKET_EVENT_TASK_CREATED: 'taskCreated',
  WEBSOCKET_EVENT_TASK_UPDATED: 'taskUpdated',
  WEBSOCKET_EVENT_ESTATE_SYNC_PUBLISHING: 'landlord:publishedToMarketPlace',
  WEBSOCKET_EVENT_ESTATE_SYNC_PUBLISHING_ERROR: 'landlord:publishToMarketPlaceError',
  WEBSOCKET_EVENT_ESTATE_SYNC_POSTING: 'landlord:postingToEstateSync',
  WEBSOCKET_EVENT_ESTATE_PUBLISH_APPROVED: 'landlord:estatePublishApproved',
  WEBSOCKET_EVENT_ESTATE_PUBLISH_DECLINED: 'landlord:estatePublishDeclined',
  WEBSOCKET_EVENT_CHECKOUT_SESSION_FAILED: 'landlord:subscriptionFailed',
  WEBSOCKET_EVENT_ESTATE_UNPUBLISHED_BY_ADMIN: 'landlord:estateUnpublishedByAdmin',
  WEBSOCKET_EVENT_ESTATE_UNPUBLISHED: 'landlord:estateUnpublished',
  WEBSOCKET_EVENT_ESTATE_DEACTIVATED: 'landlord:estateDeactivated',

  SET_EMPTY_IP_BASED_USER_INFO_ON_LOGIN: true,

  // MATCH WEB SOCKET
  WEBSOCKET_EVENT_MATCH: 'matchChanged',
  WEBSOCKET_EVENT_MATCH_STAGE: 'matchStageChanged',
  // if address valid from  importing estates, websocket will be emitted
  WEBSOCKET_EVENT_VALID_ADDRESS: 'addressValid',
  WEBSOCKET_EVENT_IMPORT_EXCEL: 'importedExcel',
  WEBSOCKET_EVENT_IMPORT_EXCEL_PROGRESS: 'progressingImportedExcel',
  WEBSOCKET_EVENT_MEMBER_INVITATION: 'memberInvitation',
  MATCH_SCORE_GOOD_MATCH: 80,

  IMPORT_TYPE_EXCEL: 'excel',
  IMPORT_TYPE_OPENIMMO: 'openimmo',
  IMPORT_ENTITY_ESTATES: 'estates',

  IMPORT_ACTION_IMPORT: 'import',
  IMPORT_ACTION_EXPORT: 'export',

  ROOM_DEFAULT_ORDER: 100000,

  IMPORT_ACTIVITY_PENDING: 'pending',
  IMPORT_ACTIVITY_DONE: 'done',

  LOW_MATCH_ICON: 'RED', // 40, 50, 60
  MEDIUM_MATCH_ICON: 'YELLOW', // 70, 80
  SUPER_MATCH_ICON: 'GREEN', // 90, 95, 100

  MATCH_HOUSEHOLD_HAS_CHILD_LABEL: 'Has child',
  MATCH_HOUSEHOLD_NO_CHILD_LABEL: 'No child',

  INCOME_TYPE_EMPLOYEE_LABEL: 'Employee',
  INCOME_TYPE_WORKER_LABEL: 'Worker',
  INCOME_TYPE_UNEMPLOYED_LABEL: 'Unemployed',
  INCOME_TYPE_CIVIL_SERVANT_LABEL: 'Civil servant',
  INCOME_TYPE_FREELANCER_LABEL: 'Freelancer',
  INCOME_TYPE_HOUSE_WORK_LABEL: 'Housekeeper',
  INCOME_TYPE_PENSIONER_LABEL: 'Pensioner',
  INCOME_TYPE_SELF_EMPLOYED_LABEL: 'Self-Employeed',
  INCOME_TYPE_TRAINEE_LABEL: 'Trainee',
  INCOME_TYPE_OTHER_BENEFIT_LABEL: 'Other benefit',
  INCOME_TYPE_CHILD_BENEFIT_LABEL: 'Child benefit',

  DOC_INCOME_PROOF_LABEL: 'Income proof',
  DOC_RENT_ARREARS_LABEL: 'Rent arrears',
  DOC_CREDIT_SCORE_LABEL: 'Credit score',
  FILE_LIMIT_LENGTH: 5,

  GENERAL_PERCENT: {
    let: 49.9,
    void: 37.5
  },
  LEASE_CONTRACT_PERCENT: {
    let: 16.7,
    void: 12.5
  },
  PROPERTY_DETAILS_PERCENT: {
    let: 16.7,
    void: 12.5
  },
  TENANT_PREFERENCES_PERCENT: {
    let: 0,
    void: 12.5
  },
  VISIT_SLOT_PERCENT: {
    let: 0,
    void: 12.5
  },
  IMAGE_DOC_PERCENT: {
    let: 16.7,
    void: 12.5
  },

  ESTATE_COMPLETENESS_BREAKPOINT: 80,
  COMPLETE_CERTAIN_PERCENT: 'complete_certain_percent',
  PUBLISH_ESTATE: 'publish_estate',
  CONNECT_ESTATE: 'connect_estate',

  COMPLETE_CERTAIN_PERCENT_EMAIL_SUBJECT: 'Landlord Completed 80% of his/her first Estate(s)',
  PUBLISH_ESTATE_EMAIL_SUBJECT: 'Landlord Published his/her first Estate(s)',
  CONNECT_ESTATE_EMAIL_SUBJECT: 'Landlord Connected his/her first Estate(s)',

  SEND_TO_SUPPORT_HTML_MESSAGE_TEMPLATE: `
<p>[SUBJECT]</p>
<p>Landlord Info: <strong>[LANDLORD]</strong></p>
<p>Estates: </p><ul>[ESTATES]</ul>
`,
  SEND_TO_SUPPORT_TEXT_MESSAGE_TEMPLATE: `
[SUBJECT]
Landlord Info: [LANDLORD]
Estates: [ESTATES]
`,

  BUILDING_AMENITIES_ORDER: [
    'Elevator',
    'Cellar',
    'Common room',
    'Parking space',
    'Bicycle storage room',
    'Garage',
    'Intercom system',
    'Thermal insulation',
    'Renewed facade',
    'Exclusive lighting',
    'High quality entrance hall',
    'Mirror',
    'Marble',
    'House entrance door not lockable'
  ],
  APARTMENT_AMENITIES_ORDER: [
    'Furnished',
    'Balcony',
    'Storage room',
    'South facing',
    'Roller shutters',
    'Mainly underfloor heating',
    'Tiles',
    'Wainscoting',
    'Loggia',
    'Roof floor',
    'Bright',
    'Roof floor',
    'Single glazing',
    'Soundproof windows',
    'High quality parquet',
    'Exclusive/high quality/luxury',
    'Panoramic view',
    'Natural/artificial stone',
    'Additional burglar alarm',
    'Thermal insulation glazing',
    'Fireplace',
    'Stucco',
    'Winter/roof garden',
    'Low barrier cut',
    'Stucco',
    'Washing machine not placeable',
    'Poor cut'
  ],
  VINCINITY_AMENITIES_ORDER: [
    'Preferred city location',
    'Car parking',
    'Bicycle parking',
    'Childrens playground',
    'Rest Areas', // Park actually
    'In Green',
    'Quiet',
    'Garden',
    'Courtyard',
    'Benches',
    'Lighting',
    'Sidewalk paving',
    'Polluted by traffic noise',
    'Odorous',
    'Heavily neglected'
  ],
  SEND_EMAIL_TO_OHNEMAKLER_SUBJECT: 'Breeze: Prospect requests from ',
  SEND_EMAIL_TO_WOHNUNGSHELDEN_SUBJECT: 'Breeze: Interessentenanfragen vom ',
  SEND_EMAIL_TO_OHNEMAKLER_CONTENT: 'I am interested in this apartment.',

  THIRD_PARTY_OFFER_SOURCE_OHNE_MAKLER: 'ohnemakler',
  THIRD_PARTY_OFFER_SOURCE_GEWOBAG: 'gewobag',
  OHNE_MAKLER_ESTATE_TYPE_VALUE_TO_QUALIFY: 'for rent',
  OHNE_MAKLER_ESTATE_OBJEKTART_TO_QUALIFY: [
    'Wohnung',
    'Haus',
    'Möbliertes Wohnen / Wohnen auf Zeit',
    'Zimmer'
  ],

  OHNE_MAKLER_DEFAULT_PREFERENCES_FOR_MATCH_SCORING: {
    income_sources: [
      'employee',
      'worker',
      'unemployed',
      'civil_servant',
      'freelancer',
      'housewife_husband',
      'pensioner',
      'self',
      'trainee'
    ],
    credit_history_status: [{ status: 1 }],
    budget: 30,
    rent_arrears: false,
    min_age: 25,
    max_age: 65,
    pets_allowed: 2, // PETS_SMALL
    family_size_min: 1,
    family_size_max: 2
  },
  GEWOBAG_DEFAULT_PREFERENCE_FOR_MATCH_SCORING: {
    credit_history_status: 1, // NO_NEGATIVE
    budget: 30,
    rent_arrears: false,
    min_age: 25,
    max_age: 65,
    pets_allowed: 2, // PETS_SMALL
    family_size_min: 1,
    family_size_max: 2
  },
  THIRD_PARTY_OFFER_SOURCES: ['ohnemakler', 'gewobag'],
  THIRD_PARTY_OFFER_PROVIDER_INFORMATION: {
    ohnemakler: {
      name: 'Ohne-makler.net',
      url: 'https://www.ohne-makler.net/',
      logo: 'https://www.ohne-makler.net/static/img/logo-dark%402x.png'
    },
    gewobag: {
      name: 'Gewobag',
      url: 'https://www.gewobag.de/',
      logo: 'APP_URL/img/gewobag.png'
    }
  },
  REQUIRED_INCOME_PROOFS_COUNT: 3,
  VALID_INCOME_PROOFS_PERIOD: 4,
  MATCH_PERCENT_PASS: 40,
  GEWOBAG_CONTACT_REQUEST_SENDER_EMAIL: ' wohnungshelden@breeze4me.net',
  GEWOBAG_CONTACT_REQUEST_RECIPIENT_EMAIL: 'anfragen@gewobag.interessentenanfragen.de',
  GEWOBAG_EMAIL_CONTENT: 'I interessiere mich für das Objekt.',
  GEWOBAG_PROPERTIES_TO_PROCESS_PER_PULL: 30,
  GEWOBAG_FTP_BUCKET: 'breeze-ftp-files',
  THIRD_PARTY_OFFER_HOUSE_TYPE: 'house_type',
  THIRD_PARTY_OFFER_APARTMENT_TYPE: 'apt_type',
  THIRD_PARTY_OFFER_PROPERTY_TYPE: 'property_type',
  PREPARING_TO_UPLOAD: 'landlord.web.my-properties.txt_preparingtoupload', // Uploading
  PROPERTY_HANDLE_FINISHED: 'landlord.web.my-properties.txt_uploadpropertiescompleted',

  THIRD_PARTY_PUBLISHERS: ['immowelt', 'immobilienscout-24', 'ebay-kleinanzeigen'],
  ESTATE_SYNC_PUBLISH_PROVIDER_IMMOWELT: 'immowelt',
  ESTATE_SYNC_PUBLISH_PROVIDER_IS24: 'immobilienscout-24',
  ESTATE_SYNC_PUBLISH_PROVIDER_EBAY: 'ebay-kleinanzeigen',

  ESTATE_SYNC_LISTING_STATUS_PUBLISHED: ESTATE_SYNC_LISTING_STATUS.PUBLISHED,
  ESTATE_SYNC_LISTING_STATUS_DELETED: ESTATE_SYNC_LISTING_STATUS.DELETED,
  ESTATE_SYNC_LISTING_STATUS_INITIALIZED: ESTATE_SYNC_LISTING_STATUS.INITIALIZED,
  ESTATE_SYNC_LISTING_STATUS_POSTED: ESTATE_SYNC_LISTING_STATUS.POSTED,
  ESTATE_SYNC_LISTING_STATUS_ERROR_FOUND: ESTATE_SYNC_LISTING_STATUS.ERROR_FOUND,
  ESTATE_SYNC_LISTING_STATUS_SCHEDULED_FOR_DELETE: ESTATE_SYNC_LISTING_STATUS.SCHEDULED_FOR_DELETE,

  ESTATE_SYNC_CREDENTIAL_TYPE_BREEZE: ESTATE_SYNC_CREDENTIAL_TYPE.BREEZE,
  ESTATE_SYNC_CREDENTIAL_TYPE_USER: ESTATE_SYNC_CREDENTIAL_TYPE.USER,

  ADMIN_URLS: {
    localhost: 'http://localhost:3001',
    development: 'https://development.d2x826avxkg7om.amplifyapp.com',
    staging: 'https://staging.d2x826avxkg7om.amplifyapp.com',
    preprod: 'https://preprod.d2x826avxkg7om.amplifyapp.com',
    production: 'https://master.d2x826avxkg7om.amplifyapp.com'
  },

  LANDLORD_REQUEST_PUBLISH_EMAIL_SUBJECT: 'Landlord Request to Publish an Estate',

  LIKED_BUT_NOT_KNOCKED_FOLLOWUP_HOURS_AFTER: 24,

  OUTSIDE_LANDLORD_INVITE_TYPE: 'outside_landlord_invitation',
  OUTSIDE_TENANT_INVITE_TYPE: 'outside_tenant_invitation',
  OUTSIDE_PROSPECT_KNOCK_INVITE_TYPE: 'outside_prospect_knock',

  PAYMENT_METHOD_STRIPE: 'stripe',
  PAYMENT_METHOD_PAYPAL: 'paypal',

  PAID_PENDING_STATUS: 1,
  PAID_PARTIALY_STATUS: 2,
  PAID_COMPLETE_STATUS: 3,
  PAID_REFUNDED: 4,
  PAID_FAILED: 5,

  PAY_MODE_UPFRONT: 1,
  PAY_MODE_ONE_TIME: 2,
  PAY_MODE_RECURRING: 3,
  PAY_MODE_USAGE: 4,

  PRICE_MEMBERSHIP: 1,
  PRICE_MATCH: 2,
  PRICE_CONNECT: 3,

  PUBLISH_STATUS_INIT: PUBLISH_STATUS.INIT,
  PUBLISH_STATUS_BY_LANDLORD: PUBLISH_STATUS.BY_LANDLORD,
  PUBLISH_STATUS_APPROVED_BY_ADMIN: PUBLISH_STATUS.APPROVED_BY_ADMIN,
  PUBLISH_STATUS_DECLINED_BY_ADMIN: PUBLISH_STATUS.DECLINED_BY_ADMIN,

  PUBLISH_PROPERTY: 'publish',
  UNPUBLISH_PROPERTY: 'unpublish',
  DEACTIVATE_PROPERTY: 'deactivate',
  PUBLISH_OFFLINE_PROPERTY: 'offlinePublish',

  PUBLISH_TYPE_ONLINE_MARKET: 1,
  PUBLISH_TYPE_OFFLINE_MARKET: 2,

  ESTATE_NO_IMAGE_COVER_URL: 'https://breeze-files-dev.s3.eu-central-1.amazonaws.com/no-cover.png',

  MEMBER_TRIAL_PERIOD: 7, // trial period 7 days

  ACCOUNT_CREATION_EMAIL_NOTIFICATION_RECIPIENTS: ['support@breeze4me.de', 'mehram@breeze4me.de'],
  LANDLORD_ACCOUNT_CREATION_EMAIL_NOTIFICATION_SUBJECT: 'New Landlord Account Created!',

  MATCH_TYPE_MATCH: 'match',
  MATCH_TYPE_BUDDY: 'buddy',
  MATCH_TYPE_MARKET_PLACE: 'listing',

  FRONTEND_USED_WEB: 'web',
  FRONTEND_USED_MOBILE: 'mobile',

  IS24_REDIRECT_URL: {
    localhost: 'https://api-dev-new.breeze4me.de/api/v1/estate-sync-is24',
    development: 'https://api-dev-new.breeze4me.de/api/v1/estate-sync-is24',
    staging: 'https://api-staging.breeze4me.de/api/v1/estate-sync-is24',
    preprod: 'https://api-preprod.breeze4me.de/api/v1/estate-sync-is24',
    production: 'https://api.breeze4me.de/api/v1/estate-sync-is24'
  },

  WEB_APP_URL: {
    localhost: 'http://localhost:3002',
    development: 'https://app-dev.breeze4me.de',
    staging: 'https://app-staging.breeze4me.de',
    preprod: 'https://app-preprod.breeze4me.de',
    production: 'https://app.breeze4me.de'
  },

  COUNTRIES: [
    { country: 'Germany', other_name: 'Deutschland', country_code: 'de' },
    { country: 'Austria', other_name: 'Österreich', country_code: 'at' },
    { country: 'Switzerland', other_name: 'Schweiz', country_code: 'ch' }
  ],

  RENT_DURATION_LONG: 'long',
  RENT_DURATION_SHORT: 'short',
  QUEUE_JOB_URGENT: 100,

  CITIES_AUTOCOMPLETE_MAX_COUNT: 10,
  WEBSOCKET_TENANT_REDIS_KEY: 'tenant',
  WEBSOCKET_LANDLORD_REDIS_KEY: 'landlord',
  WEBSOCKET_TASK_REDIS_KEY: 'task',

  MARKETPLACE_LIST: {
    immowelt: 'landlord.web.my-properties.txt_immowelt',
    'immobilienscout-24': 'landlord.web.my-properties.txt_immobilienscout24',
    'ebay-kleinanzeigen': 'landlord.web.my-properties.txt_ebaykleinanzeigen'
  },

  SHORTENURL_LENGTH: 10,
  EXPIRED_FINAL_CONFIRM_PERIOD: 2, // hourly based

  ROOM_INTERVAL_COUNT: 1,
  MAX_ROOM_COUNT: 10,
  SPACE_INTERVAL_COUNT: 7.5,
  MAX_SPACE_COUNT: 500,
  RENT_INTERVAL_COUNT: 100,
  MAX_RENT_COUNT: 5000,
  FLOOR_INTERVAL_COUNT: 1,
  MAX_FLOOR_COUNT: 20,

  FURNISHED_GERMAN_NAME: 'Möbliert',

  CERT_CATEGORY_A: 'prospect.profile.adult.apartment.txt_PublicCertificateCategoryA',
  CERT_CATEGORY_B: 'prospect.profile.adult.apartment.txt_PublicCertificateCategoryB',
  CERT_CATEGORY_C: 'prospect.profile.adult.apartment.txt_PublicCertificateCategoryC',
  CERT_CATEGORY_I: 'prospect.profile.adult.apartment.txt_PublicCertificateCategoryI',
  CERT_CATEGORY_II: 'prospect.profile.adult.apartment.txt_PublicCertificateCategoryII',
  CERT_CATEGORY_III: 'prospect.profile.adult.apartment.txt_PublicCertificateCategoryIII',
  CERT_CATEGORY_IV: 'prospect.profile.adult.apartment.txt_PublicCertificateCategoryIV',
  CERT_CATEGORY_100: 'prospect.profile.adult.apartment.txt_PublicCertificateCategory100',
  CERT_CATEGORY_140: 'prospect.profile.adult.apartment.txt_PublicCertificateCategory140',
  CERT_CATEGORY_160: 'prospect.profile.adult.apartment.txt_PublicCertificateCategory160',
  CERT_CATEGORY_180: 'prospect.profile.adult.apartment.txt_PublicCertificateCategory180',
  CERT_CATEGORY_220: 'prospect.profile.adult.apartment.txt_PublicCertificateCategory220',
  CERT_CATEGORY_NOT: 'prospect.profile.adult.apartment.txt_PublicCertificateCategoryBWB',

  INCOME_CONTRACT_DURATION_UNLIMITED: 1,
  INCOME_CONTRACT_DURATION_LIMITED: 2,

  MARITAL_SINGLE: 1,
  MARITAL_MARRIED: 2,
  MARITAL_PERMANENT_SEPRATED: 3,
  MARITAL_DIVORCED: 4,
  MARITAL_WIDOWED: 5,
  MARITAL_COHABITATION: 6,
  MARITAL_REGISTERED_COHABITATION: 7,

  MANDATORY_AMENITIES: {
    FURNISHED: 'furnished',
    FITTED_KITCHEN: 'fitted_kitchen',
    BARRIER_FREE: 'landlord.property.details.building_amenities.barrier_free',
    ELEVATOR: 'elevator',
    BALCONY: 'apt_balcony'
  },
  UNIT_SHEET: 1,
  BUILDING_SHEET: 2,
  CATEGORY_SHEET: 3,

  CREDIT_HISTORY_STATUS_NO_NEGATIVE_DATA: 1,
  CREDIT_HISTORY_STATUS_SOME_NEGATIVE_DATA: 2,
  CREDIT_HISTORY_STATUS_ENFORCEABLE_CLAIMS: 3,

  IS24_PUBLISHING_STATUS_NO_STATUS: 0,
  IS24_PUBLISHING_STATUS_INIT: 1,
  IS24_PUBLISHING_STATUS_POSTED: 2,
  IS24_PUBLISHING_STATUS_PUBLISHED: 3,

  GEWOBAG_ACCOUNT_USER_ID: 23288,
  GEWOBAG_MARKETPLACE_PUBLISHERS: ['immowelt', 'immobilienscout-24', 'ebay-kleinanzeigen']
}

module.exports = {
  ...constants,
  SUPPORTED_LANGUAGES,
  APP_CONFIG,
  APP_ROLES,
  FILE_TYPE,
  ENVIRONMENT,
  USER_ACTIVATION_STATUS,
  BUILDING_STATUS,
  ESTATE_SYNC_LISTING_STATUS,
  DEVICE_TYPE,
  PROPERTY_TYPE,
  APARTMENT_TYPE,
  HEATING_TYPE,
  FIRING_TYPE,
  PETS,
  PARKING_SPACE_TYPE,
  OPTIONS_TYPE,
  CURRENCY,
  SALUTATION_LABEL,
  USER_STATUS,
  PUBLISH_STATUS,
  ESTATE_SYNC_CREDENTIAL_TYPE
}
