'use strict'

const Schema = use('Schema')
const Database = use('Database')

const sql = `
INSERT INTO options (title, type)
VALUES ('bicycle_storage_room', 'build'),
       ('common_room', 'build'),
       ('high_quality_entrance_hall', 'build'),
       ('mirror', 'build'),
       ('marble', 'build'),
       ('exclusive_lighting', 'build'),
       ('renewed_facade', 'build'),
       ('intercom_system_with_electric_door_opener', 'build'),
       ('elevator_5_floors_', 'build'),
       ('thermal_insulation', 'build'),
       ('cellar', 'build'),
       ('house_entrance_door_not_lockable', 'build'),
       ('garage', 'build'),
       ('parking_space', 'build'),
       ('elevator', 'build'),
       ('storage_room', 'apt'),
       ('balcony', 'apt'),
       ('loggia', 'apt'),
       ('winter_roof_garden', 'apt'),
       ('mainly_underfloor_heating', 'apt'),
       ('roller_shutters', 'apt'),
       ('stucco', 'apt'),
       ('wainscoting', 'apt'),
       ('heating_pipes_not_visible', 'apt'),
       ('poor_cut', 'apt'),
       ('additional_burglar_alarm', 'apt'),
       ('thermal_insulation_glazing', 'apt'),
       ('single_glazing', 'apt'),
       ('washing_machine_not_placeable', 'apt'),
       ('high_quality_parquet', 'apt'),
       ('natural_artificial_stone', 'apt'),
       ('tiles', 'apt'),
       ('soundproof_windows', 'apt'),
       ('low_barrier_cut', 'apt'),
       ('fireplace', 'apt'),
       ('panoramic_view', 'apt'),
       ('south_facing', 'apt'),
       ('bright', 'apt'),
       ('roof_floor', 'apt'),
       ('exclusive_high_quality_luxury', 'apt'),
       ('preferred_city_location', 'out'),
       ('quiet', 'out'),
       ('polluted_by_traffic_noise', 'out'),
       ('heavily_neglected', 'out'),
       ('odorous', 'out'),
       ('childrens_playground', 'out'),
       ('benches', 'out'),
       ('rest_areas', 'out'),
       ('sidewalk_paving', 'out'),
       ('in_green', 'out'),
       ('lighting', 'out'),
       ('car_parking', 'out'),
       ('garden', 'out'),
       ('bicycle_parking', 'out'),
       ('courtyard', 'out'),
       ('with_window', 'kitchen'),
       ('sufficient_ventilation', 'kitchen'),
       ('separate_kitchen', 'kitchen'),
       ('fitted_kitchen', 'kitchen'),
       ('ceramic_hob', 'kitchen'),
       ('induction_hob', 'kitchen'),
       ('refrigerator', 'kitchen'),
       ('sink', 'kitchen'),
       ('gas_electric_stove_with_oven', 'kitchen'),
       ('high_quality_tiles', 'kitchen'),
       ('high_quality_linoleum', 'kitchen'),
       ('parquet', 'kitchen'),
       ('terrazzo', 'kitchen'),
       ('high_quality_laminate', 'kitchen'),
       ('central_hot_water_supply', 'kitchen'),
       ('extractor_fan', 'kitchen'),
       ('dishwasher', 'kitchen'),
       ('wood_coal_heating', 'kitchen'),
       ('large_washbasin', 'bad'),
       ('high_quality_bathroom_furniture', 'bad'),
       ('corner_bath', 'bad'),
       ('round_tub', 'bad'),
       ('bath_with_ventilation', 'bad'),
       ('second_wc', 'bad'),
       ('underfloor_heating', 'bad'),
       ('wall_covering', 'bad'),
       ('floor_covering', 'bad'),
       ('wall_hung_wc', 'bad'),
       ('towel_warmer', 'bad'),
       ('shower_tray', 'bad'),
       ('shower_cubicle', 'bad'),
       ('central_hot_water', 'bad'),
       ('with_window', 'bad'),
       ('storage_room', 'room'),
       ('balcony', 'room'),
       ('loggia', 'room'),
       ('winter_roof_garden', 'room'),
       ('mainly_underfloor_heating', 'room'),
       ('roller_shutters', 'room'),
       ('stucco', 'room'),
       ('wainscoting', 'room'),
       ('heating_pipes_not_visible', 'room'),
       ('poor_cut', 'room'),
       ('additional_burglar_alarm', 'room'),
       ('thermal_insulation_glazing', 'room'),
       ('single_glazing', 'room'),
       ('washing_machine_not_placeable', 'room'),
       ('high_quality_parquet', 'room'),
       ('natural_artificial_stone', 'room'),
       ('tiles', 'room'),
       ('soundproof_windows', 'room'),
       ('low_barrier_cut', 'room'),
       ('fireplace', 'room'),
       ('panoramic_view', 'room'),
       ('south_facing', 'room'),
       ('bright', 'room'),
       ('roof_floor', 'room'),
       ('exclusive_high_quality_luxury', 'room');
`

class OptionsSchema extends Schema {
  up() {
    this.schedule(async (trx) => {
      await Database.table('options').delete()
      await Database.raw(`SELECT setval('options_id_seq', 1)`)
      await Database.raw(sql)
    })
  }

  down() {}
}

module.exports = OptionsSchema
