'use strict'

const Schema = use('Schema')
const Database = use('Database')

const sql = `
INSERT INTO professions (value, title_en, title_de, type) VALUES
('agriculture', 'Agriculture', 'Landwirtschaft', 111),
('agricultural_engineering', 'Agricultural Engineering', 'Landtechnik', 111),
('agricultural_experts', 'Agricultural Experts', 'Landwirtschaftliche Sachverständige', 111),
('agricultural_technical_laboratory', 'Agricultural-Technical Laboratory', 'landwirtschaftlich-technischen Laboratorium', 111),
('livestock_farming_except_poultry_farming', 'Livestock Farming (Except Poultry Farming)', 'Nutztierhaltung (außer Geflügelhaltung)', 112),
('poultry_farming', 'Poultry Farming', 'Geflügelhaltung', 112),
('beekeeping', 'Beekeeping', 'Imkerei', 112),
('animal_husbandry', 'Animal Husbandry', 'Tierwirtschaft', 112),
('horse_industry', 'Horse Industry', 'Pferdewirtschaft', 113),
('horse_industry_horse_breeding', 'Horse Industry - Horse Breeding', 'Pferdewirtschaft - Pferdezucht', 113),
('horse_industry_riding', 'Horse Industry - Riding', 'Pferdewirtschaft - Reiten', 113),
('farrier_blacksmiths', 'Farrier Blacksmiths', 'Hufbeschlagschmiede/-schmiedinnen', 113),
('coachmen', 'Coachmen', 'Kutscher/innen', 113),
('fishing_industry', 'Fishing Industry', 'Fischwirtschaft', 114),
('fish_farming', 'Fish Farming', 'Fischzucht', 114),
('fishing', 'Fishing', 'Fischerei', 114),
('animal_care', 'Animal Care', 'Tierpflege', 115),
('farm_animal_care', 'Farm Animal Care', 'Nutztierpflege', 115),
('house_and_zoo_animal_care', 'House And Zoo Animal Care', 'Haus- und Zootierpflege', 115),
('viticulture', 'Viticulture', 'Weinbau', 116),
('forestry', 'Forestry', 'Forstwirtschaft', 117),
('nature_and_landscape_conservation', 'Nature And Landscape Conservation', 'Natur- und Landschaftspflege', 117),
('hunting_and_game_reserve', 'Hunting And Game Reserve', 'Jagdwirtschaft und Wildhege', 117),
('collecting_and_obtaining_plants_and_other_natural_products', 'Collecting And Obtaining Plants And Other Natural Products', 'Sammeln und Gewinnen von Pflanzen und anderen Naturprodukten', 117),
('forestry_and_hunting_landscape_maintenance', 'Forestry And Hunting, Landscape Maintenance', 'Forst- und Jagdwirtschaft, Landschaftspflege', 117),
('horticulture', 'Horticulture', 'Gartenbau', 121),
('fruit_and_vegetable_growing', 'Fruit And Vegetable Growing', 'Obst- und Gemüsebau', 121),
('occupations_in_tree_nursery_perennial_gardening_and_growing_of_ornamental_plants', 'Occupations In Tree Nursery, Perennial Gardening And Growing Of Ornamental Plants', 'Berufe in Baumschule, Staudengärtnerei und Zierpflanzenbau', 121),
('cemetery_nursery', 'Cemetery Nursery', 'Friedhofsgärtnerei', 121),
('gardening_landscaping_and_sports_field_construction', 'Gardening, Landscaping And Sports Field Construction', 'Garten-, Landschafts- und Sportplatzbau', 121),
('floristry', 'Floristry', 'Floristik', 122),
('mining_and_opencast_mining', 'Mining And Opencast Mining', 'Berg- und Tagebau', 211),
('blasting_technology', 'Blasting Technology', 'Sprengtechnik', 211),
('mining_and_opencast_mining_and_blasting_technology', 'Mining And Opencast Mining And Blasting Technology', 'Berg- und Tagebau und Sprengtechnik', 211),
('processing_and_processing_of_natural_stone_and_minerals_and_manufacturing_of_building_materials', 'Processing And Processing Of Natural Stone And Minerals And Manufacturing Of Building Materials', 'Naturstein- und Mineralaufbereitung und -verarbeitung und Baustoffherstellung', 212),
('natural_stone_and_mineral_processing', 'Natural Stone And Mineral Processing', 'Naturstein- und Mineralaufbereitung', 212),
('building_material_production', 'Building Material Production', 'Baustoffherstellung', 212),
('stonemasonry', 'Stonemasonry', 'Steinmetztechnik', 212),
('glass_manufacturing', 'Glass Manufacturing', 'Glasherstellung', 213),
('glass_apparatus_construction', 'Glass Apparatus Construction', 'Glasapparatebau', 213),
('industrial_glass_blowing', 'Industrial Glass Blowing', 'industriellen Glasbläserei', 213),
('glass_finishing', 'Glass Finishing', 'Glasveredelung', 213),
('glass_apparatus_adjustment', 'Glass Apparatus Adjustment', 'Glasapparatejustierung', 213),
('fine_optics', 'Fine Optics', 'Feinoptik', 213),
('industrial_glass_manufacturing_and_processing', 'Industrial Glass Manufacturing And Processing', 'Industrielle Glasherstellung und -verarbeitung', 213),
('industrial_ceramics_process_and_plant_engineering', 'Industrial Ceramics (Process And Plant Engineering)', 'Industriekeramik (Verfahrens- und Anlagentechnik)', 214),
('industrial_ceramics_model_technology', 'Industrial Ceramics (Model Technology)', 'Industriekeramik (Modelltechnik)', 214),
('industrial_ceramics_manufacture_and_processing', 'Industrial Ceramics Manufacture And Processing', 'Industrielle Keramikherstellung und -verarbeitung', 214),
('plastic_and_rubber_production', 'Plastic And Rubber Production', 'Kunststoff- und Kautschukherstellung', 221),
('tire_and_vulcanization_technology', 'Tire And Vulcanization Technology', 'Reifen- und Vulkanisationstechnik', 221),
('plastic_and_rubber_manufacture_and_processing', 'Plastic And Rubber Manufacture And Processing', 'Kunststoff- und Kautschukherstellung und -verarbeitung', 221),
('paint_and_lacquer_technology', 'Paint And Lacquer Technology', 'Farb- und Lacktechnik', 222),
('vehicle_painting', 'Vehicle Painting', 'Fahrzeuglackierung', 222),
('paint_laboratory', 'Paint Laboratory', 'Lacklaboratorium', 222),
('wood_working_and_processing', 'Wood Working And Processing', 'Holzbe- und -verarbeitung', 223),
('wood_drying_and_conservation', 'Wood Drying And Conservation', 'Holztrocknung und -konservierung', 223),
('production_of_wood_materials_and_components', 'Production Of Wood Materials And Components', 'Produktion von Holzwerkstoffen und -bauteilen', 223),
('production_of_finished_products_from_wood_and_wood_based_materials', 'Production Of Finished Products From Wood And Wood-Based Materials', 'Produktion von Fertigprodukten aus Holz und Holzwerkstoffen', 223),
('wood_furniture_and_interior_construction', 'Wood, Furniture And Interior Construction', 'Holz-, Möbel- und Innenausbau', 223),
('wickerwork_designers_brush_makers_and_paintbrush_makers', 'Wickerwork Designers, Brush Makers And Paintbrush Makers', 'Flechtwerkgestalter/innen, Bürsten- und Pinselmacher/innen', 223),
('paper_and_packaging_technology', 'Paper And Packaging Technology', 'Papier- und Verpackungstechnik', 231),
('papermaking', 'Papermaking', 'Papierherstellung', 231),
('paper_processing_and_packaging_technology', 'Paper Processing And Packaging Technology', 'Papierverarbeitung und Verpackungstechnik', 231),
('digital_and_print_media_design', 'Digital And Print Media Design', 'Digital- und Printmediengestaltung', 232),
('graphic_communication_and_photo_design', 'Graphic, Communication And Photo Design', 'Grafik-, Kommunikations- und Fotodesign', 232),
('technical_media_design', 'Technical Media Design', 'technischen Mediengestaltung', 232),
('technical_media_design', 'Technical Media Design', 'Technische Mediengestaltung', 232),
('photo_technology', 'Photo Technology', 'Fototechnik', 233),
('photography', 'Photography', 'Fotografie', 233),
('photo_technology_and_photography', 'Photo Technology And Photography', 'Fototechnik und Fotografie', 233),
('printing_technology', 'Printing Technology', 'Drucktechnik', 234),
('bookbinding_and_print_finishing', 'Bookbinding And Print Finishing', 'Buchbinderei und Druckweiterverarbeitung', 234),
('printing_technology_and_processing_bookbinding', 'Printing Technology And Processing, Bookbinding', 'Drucktechnik und -weiterverarbeitung, Buchbinderei', 234),
('metal_production', 'Metal Production', 'Metallerzeugung', 241),
('metallurgy', 'Metallurgy', 'Hüttentechnik', 241),
('metal_forming', 'Metal Forming', 'Metallumformung', 241),
('industrial_foundry', 'Industrial Foundry', 'industriellen Gießerei', 241),
('artisanal_metal_and_bell_foundry', 'Artisanal Metal And Bell Foundry', 'handwerklichen Metall- und Glockengießerei', 241),
('metalworking', 'Metalworking', 'Metallbearbeitung', 242),
('non_cutting_metalworking', 'Non-Cutting Metalworking', 'spanlosen Metallbearbeitung', 242),
('abrasive_metalworking', 'Abrasive Metalworking', 'schleifenden Metallbearbeitung', 242),
('metal_cutting', 'Metal Cutting', 'spanenden Metallbearbeitung', 242),
('metal_processing_by_laser_beam', 'Metal Processing By Laser Beam', 'Metallbearbeitung durch Laserstrahl', 242),
('metal_surface_treatment', 'Metal Surface Treatment', 'Metalloberflächenbehandlung', 243),
('metal_construction', 'Metal Construction', 'Metallbau', 244),
('welding_and_connection_technology', 'Welding And Connection Technology', 'Schweiß- und Verbindungstechnik', 244),
('industrial_divers_and_other_diving_professions', 'Industrial Divers And Other Diving Professions', 'Industrietaucher/innen und andere Taucherberufe', 244),
('metal_construction_and_welding_technology', 'Metal Construction And Welding Technology', 'Metallbau und Schweißtechnik', 244),
('precision_engineering', 'Precision Engineering', 'Feinwerktechnik', 245),
('tool_technology', 'Tool Technology', 'Werkzeugtechnik', 245),
('watchmaking', 'Watchmaking', 'Uhrmacherhandwerk', 245),
('precision_and_tool_technology', 'Precision And Tool Technology', 'Feinwerk- und Werkzeugtechnik', 245),
('mechanical_and_industrial_engineering', 'Mechanical And Industrial Engineering', 'Maschinenbau- und Betriebstechnik', 251),
('machine_and_device_assemblers', 'Machine And Device Assemblers', 'Maschinen- und Gerätezusammensetzer/innen', 251),
('machine_and_system_operators', 'Machine And System Operators', 'Maschinen- und Anlagenführer/innen', 251),
('technical_service_staff_in_maintenance_and_repair', 'Technical Service Staff In Maintenance And Repair', 'Technische Servicekräfte in Wartung und Instandhaltung', 251),
('vehicle_technology', 'Vehicle Technology', 'Fahrzeugtechnik', 252),
('automotive_engineering', 'Automotive Engineering', 'Kraftfahrzeugtechnik', 252),
('agricultural_and_construction_machinery', 'Agricultural And Construction Machinery', 'Land- und Baumaschinentechnik', 252),
('aerospace_engineering', 'Aerospace Engineering', 'Luft- und Raumfahrttechnik', 252),
('shipbuilding_technology', 'Shipbuilding Technology', 'Schiffbautechnik', 252),
('two_wheel_technology', 'Two-Wheel Technology', 'Zweiradtechnik', 252),
('vehicle_aerospace_and_shipbuilding_technology', 'Vehicle, Aerospace And Shipbuilding Technology', 'Fahrzeug-, Luft-, Raumfahrt- und Schiffbautechnik', 252),
('mechatronics_and_automation_technology', 'Mechatronics And Automation Technology', 'Mechatronik und Automatisierungstechnik', 261),
('mechatronics', 'Mechatronics', 'Mechatronik', 261),
('automation_technology', 'Automation Technology', 'Automatisierungstechnik', 261),
('building_electrics', 'Building Electrics', 'Bauelektrik', 262),
('electrical_machine_technology', 'Electrical Machine Technology', 'Elektromaschinentechnik', 262),
('energy_and_power_plant_technology', 'Energy And Power Plant Technology', 'Energie- und Kraftwerkstechnik', 262),
('regenerative_energy_technology', 'Regenerative Energy Technology', 'regenerativen Energietechnik', 262),
('electrical_engineering', 'Electrical Engineering', 'elektrischen Betriebstechnik', 262),
('line_installation_and_maintenance', 'Line Installation And Maintenance', 'Leitungsinstallation und -wartung', 262),
('energy_technology', 'Energy Technology', 'Energietechnik', 262),
('electrical_engineering', 'Electrical Engineering', 'Elektrotechnik', 263),
('information_and_telecommunications_technology', 'Information And Telecommunications Technology', 'Informations- und Telekommunikationstechnik', 263),
('microsystem_technology', 'Microsystem Technology', 'Mikrosystemtechnik', 263),
('aviation_ship_and_vehicle_electronics', 'Aviation, Ship And Vehicle Electronics', 'Luftverkehrs-, Schiffs- und Fahrzeugelektronik', 263),
('technical_research_and_development', 'Technical Research And Development', 'technischen Forschung und Entwicklung', 271),
('technical_research_and_development', 'Technical Research And Development', 'Technische Forschung und Entwicklung', 271),
('technical_draftsmen', 'Technical Draftsmen', 'Technische Zeichner/innen', 272),
('construction_and_equipment_manufacturing', 'Construction And Equipment Manufacturing', 'Konstruktion und im Gerätebau', 272),
('modelling', 'Modelling', 'Modellbau', 272),
('technical_drawing_construction_and_model_making', 'Technical Drawing, Construction And Model Making', 'Technisches Zeichnen, Konstruktion und Modellbau', 272),
('technical_production_planning_and_control', 'Technical Production Planning And Control', 'technischen Produktionsplanung und -steuerung', 273),
('technical_quality_assurance', 'Technical Quality Assurance', 'technischen Qualitätssicherung', 273),
('technical_production_planning_and_control', 'Technical Production Planning And Control', 'Technische Produktionsplanung und -steuerung', 273),
('textile_technology', 'Textile Technology', 'Textiltechnik', 281),
('textile_design', 'Textile Design', 'Textilgestaltung', 281),
('textile_manufacturing', 'Textile Manufacturing', 'Textilherstellung', 281),
('yarn_and_rope_manufacture', 'Yarn And Rope Manufacture', 'Garn- und Seilherstellung', 281),
('joinery', 'Joinery', 'Bautischlerei', 333),
('textile_finishing', 'Textile Finishing', 'Textilveredlung', 281),
('textile_technology_and_production', 'Textile Technology And Production', 'Textiltechnik und -produktion', 281),
('fashion_design', 'Fashion Design', 'Modedesign', 282),
('manufacture_of_clothing_hats_and_caps', 'Manufacture Of Clothing, Hats And Caps', 'Bekleidungs-, Hut- und Mützenherstellung', 282),
('technical_fabricators_sailmakers', 'Technical Fabricators, Sailmakers', 'Technische Konfektionäre/Konfektionärinnen, Segelmacher/innen', 282),
('upholstery_and_vehicle_interiors', 'Upholstery And Vehicle Interiors', 'Polsterei und Fahrzeuginnenausstattung', 282),
('textile_processing', 'Textile Processing', 'Textilverarbeitung', 282),
('leather_fur_production_and_processing', 'Leather, Fur Production And Processing', 'Leder-, Pelzherstellung und -verarbeitung', 283),
('leather_manufacturing', 'Leather Manufacturing', 'Lederherstellung', 283),
('saddlery_and_manufacture_of_leather_utensils', 'Saddlery And Manufacture Of Leather Utensils', 'Sattlerei und Herstellung von Lederutensilien', 283),
('shoe_manufacturing', 'Shoe Manufacturing', 'Schuhherstellung', 283),
('fur_working_and_processing', 'Fur Working And Processing', 'Pelzbe- und -verarbeitung', 283),
('beverage_production', 'Beverage Production', 'Getränkeherstellung', 291),
('brewers_and_maltsters', 'Brewers And Maltsters', 'Brauer/innen und Mälzer/innen', 291),
('wine_cooperators', 'Wine Cooperators', 'Weinküfer/innen', 291),
('distillers_and_distillers', 'Distillers And Distillers', 'Brenner/innen und Destillateure/Destillateurinnen', 291),
('fruit_juice_technique', 'Fruit Juice Technique', 'Fruchtsafttechnik', 291),
('food_and_drink_tellers', 'Food And Drink Tellers', 'Nahrungsmittel- und Getränkekoster/innen', 291),
('food_production', 'Food Production', 'Lebensmittelherstellung', 292),
('mill_product_and_feed_production', 'Mill Product And Feed Production', 'Mühlenprodukt- und Futtermittelherstellung', 292),
('bakery_and_confectionery_production', 'Bakery And Confectionery Production', 'Back- und Konditoreiwarenherstellung', 292),
('meat_processing', 'Meat Processing', 'Fleischverarbeitung', 292),
('fish_processing', 'Fish Processing', 'Fischverarbeitung', 292),
('dairy_production', 'Dairy Production', 'Milchproduktherstellung', 292),
('confectionery_production', 'Confectionery Production', 'Süßwarenherstellung', 292),
('manufacture_of_tobacco_products', 'Manufacture Of Tobacco Products', 'Tabakwarenherstellung', 292),
('food_and_luxury_food_production', 'Food And Luxury Food Production', 'Lebensmittel- und Genussmittelherstellung', 292),
('cooks', 'Cooks', 'Köche/Köchinnen', 293),
('pre_cooks_cold_and_dessert_cooks', 'Pre-Cooks, Cold And Dessert Cooks', 'Vor-, Kalt- und Süßspeisenköche/-köchinnen', 293),
('grill_roast_and_fish_cooks', 'Grill, Roast And Fish Cooks', 'Grill-, Braten- und Fischköche/-köchinnen', 293),
('food_preparation', 'Food Preparation', 'Speisenzubereitung', 293),
('construction_planning_and_supervision', 'Construction Planning And Supervision', 'Bauplanung und -überwachung', 311),
('architecture', 'Architecture', 'Architektur', 311),
('urban_and_spatial_planning', 'Urban And Spatial Planning', 'Stadt- und Raumplanung', 311),
('construction_planning_of_traffic_routes_and_facilities', 'Construction Planning Of Traffic Routes And Facilities', 'Bauplanung von Verkehrswegen und -anlagen', 311),
('water_management', 'Water Management', 'Wasserwirtschaft', 311),
('building_maintenance_and_renovation', 'Building Maintenance And Renovation', 'Bauwerkserhaltung und -erneuerung', 311),
('building_experts_and_inspectors', 'Building Experts And Inspectors', 'Bausachverständige und Baukontrolleure/-kontrolleurinnen', 311),
('construction_accounting_and_costing', 'Construction Accounting And Costing', 'Bauabrechnung und -kalkulation', 311),
('construction_planning_and_supervision_architecture', 'Construction Planning And Supervision, Architecture', 'Bauplanung und -überwachung, Architektur', 311),
('surveying_technology', 'Surveying Technology', 'Vermessungstechnik', 312),
('cartography', 'Cartography', 'Kartografie', 312),
('building_construction', 'Building Construction', 'Hochbau', 321),
('concrete_and_reinforced_concrete_construction', 'Concrete And Reinforced Concrete Construction', 'Beton- und Stahlbetonbau', 321),
('masonry', 'Masonry', 'Maurerhandwerk', 321),
('chimney_construction', 'Chimney Construction', 'Schornsteinbau', 321),
('roofing', 'Roofing', 'Dachdeckerei', 321),
('facade_construction', 'Facade Construction', 'Fassadenbau', 321),
('scaffolding', 'Scaffolding', 'Gerüstbau', 321),
('building_demolition', 'Building Demolition', 'Bauwerksabbruch', 321),
('civil_engineering', 'Civil Engineering', 'Tiefbau', 322),
('pavers_and_stone_setters', 'Pavers And Stone Setters', 'Pflasterer/Pflasterinnen und Steinsetzer/innen', 322),
('road_and_asphalt_construction', 'Road And Asphalt Construction', 'Straßen- und Asphaltbau', 322),
('track_construction', 'Track Construction', 'Gleisbau', 322),
('well_construction', 'Well Construction', 'Brunnenbau', 322),
('canal_and_tunnel_construction', 'Canal And Tunnel Construction', 'Kanal- und Tunnelbau', 322),
('culture_and_hydraulic_engineering', 'Culture And Hydraulic Engineering', 'Kultur- und Wasserbau', 322),
('floor_laying', 'Floor Laying', 'Bodenverlegung', 331),
('tile_slab_and_mosaic_laying', 'Tile, Slab And Mosaic Laying', 'Fliesen-, Platten- und Mosaikverlegung', 331),
('laying_screed_and_terrazzo', 'Laying Screed And Terrazzo', 'Estrich- und Terrazzoverlegung', 331),
('parquet_laying', 'Parquet Laying', 'Parkettverlegung', 331),
('professions_for_painting_and_varnishing_work', 'Professions For Painting And Varnishing Work', 'Berufe für Maler- und Lackiererarbeiten', 332),
('plastering_jobs', 'Plastering Jobs', 'Berufe für Stuckateurarbeiten', 332),
('structural_waterproofing', 'Structural Waterproofing', 'Bauwerksabdichtung', 332),
('wood_and_building_protection', 'Wood And Building Protection', 'Holz- und Bautenschutz', 332),
('painting_and_varnishing_plastering_work_building_waterproofing_wood_and_building_protection', 'Painting And Varnishing, Plastering Work, Building Waterproofing, Wood And Building Protection', 'Maler- und Lackierer-, Stuckateurarbeiten, Bauwerksabdichtung, Holz- und Bautenschutz', 332),
('removal_and_drywall', 'Removal And Drywall', 'Aus- und Trockenbau', 333),
('insulation', 'Insulation', 'Isolierung', 333),
('carpentry', 'Carpentry', 'Zimmerei', 333),
('glazing', 'Glazing', 'Glaserei', 333),
('roller_shutter_and_blind_construction', 'Roller Shutter And Blind Construction', 'Rollladen- und Jalousiebau', 333),
('removal_and_dry_construction_insulation_carpentry_glazing_roller_shutters_and_blinds', 'Removal And Dry Construction, Insulation, Carpentry, Glazing, Roller Shutters And Blinds', 'Aus- und Trockenbau, Isolierung, Zimmerei, Glaserei, Rollladen- und Jalousiebau', 333),
('building_technology', 'Building Technology', 'Gebäudetechnik', 341),
('site_and_equipment_attendants', 'Site And Equipment Attendants', 'Platz- und Gerätewarte/-wartinnen', 341),
('plumbing', 'Plumbing', 'Klempnerei', 342),
('sanitary_heating_and_air_conditioning_technology', 'Sanitary, Heating And Air Conditioning Technology', 'Sanitär-, Heizungs- und Klimatechnik', 342),
('furnace_and_air_heating_construction', 'Furnace And Air Heating Construction', 'Ofen- und Luftheizungsbau', 342),
('refrigeration', 'Refrigeration', 'Kältetechnik', 342),
('plumbing_plumbing_heating_and_air_conditioning', 'Plumbing, Plumbing, Heating And Air Conditioning', 'Klempnerei, Sanitär-, Heizungs- und Klimatechnik', 342),
('supply_and_disposal', 'Supply And Disposal', 'Ver- und Entsorgung', 343),
('water_supply_and_sewage_technology', 'Water Supply And Sewage Technology', 'Wasserversorgungs- und Abwassertechnik', 343),
('pipeline_construction', 'Pipeline Construction', 'Rohrleitungsbau', 343),
('waste_management', 'Waste Management', 'Abfallwirtschaft', 343),
('plant_container_and_apparatus_construction', 'Plant, Container And Apparatus Construction', 'Anlagen-, Behälter- und Apparatebau', 343),
('mathematics', 'Mathematics', 'Mathematik', 411),
('statistics', 'Statistics', 'Statistik', 411),
('math_and_statistics', 'Math And Statistics', 'Mathematik und Statistik', 411),
('biology', 'Biology', 'Biologie', 412),
('biological_technical_laboratory', 'Biological-Technical Laboratory', 'biologisch-technischen Laboratorium', 412),
('biological_preparation', 'Biological Preparation', 'biologischen Präparation', 412),
('biology_ecology', 'Biology (Ecology)', 'Biologie (Ökologie)', 412),
('biology_botany', 'Biology (Botany)', 'Biologie (Botanik)', 412),
('biology_zoology', 'Biology (Zoology)', 'Biologie (Zoologie)', 412),
('biology_microbiology', 'Biology (Microbiology)', 'Biologie (Mikrobiologie)', 412),
('biology_human_biology', 'Biology (Human Biology)', 'Biologie (Humanbiologie)', 412),
('chemistry', 'Chemistry', 'Chemie', 413),
('chemical_and_pharmaceutical_engineering', 'Chemical And Pharmaceutical Engineering', 'Chemie-und Pharmatechnik', 413),
('chemical_technical_laboratory', 'Chemical-Technical Laboratory', 'chemisch-technischen Laboratorium', 413),
('controllers_of_chemical_process_plants', 'Controllers Of Chemical Process Plants', 'Steuerer/Steuerinnen von chemischen Verfahrensanlagen', 413),
('taxers_of_crude_oil_and_natural_gas_refining_plants', 'Taxers Of Crude Oil And Natural Gas Refining Plants', 'Steuerer/Steuerinnen von Erdöl- und Erdgasraffinationsanlagen', 413),
('physics', 'Physics', 'Physik', 414),
('physical_technical_laboratory', 'Physical-Technical Laboratory', 'physikalisch-technischen Laboratorium', 414),
('materials_engineering', 'Materials Engineering', 'Werkstofftechnik', 414),
('building_material_testing', 'Building Material Testing', 'Baustoffprüfung', 414),
('geotechnics', 'Geotechnics', 'Geotechnik', 421),
('geology', 'Geology', 'Geologie', 421),
('geography', 'Geography', 'Geografie', 421),
('meteorology', 'Meteorology', 'Meteorologie', 421),
('environmental_protection_technology', 'Environmental Protection Technology', 'Umweltschutztechnik', 422),
('chimney_sweeps', 'Chimney Sweeps', 'Schornsteinfeger/innen', 422),
('environmental_management_and_advice', 'Environmental Management And Advice', 'Umweltschutzverwaltung und -beratung', 423),
('water_pollution_control_and_waste_officer', 'Water, Pollution Control And Waste Officer', 'Gewässer-, Immissionsschutz- und Abfallbeauftragte', 423),
('radiation_protection_officer', 'Radiation Protection Officer', 'Strahlenschutzbeauftragte', 423),
('environmental_management_and_advice', 'Environmental Management And Advice', 'Umweltmanagement und -beratung', 423),
('computer_science', 'Computer Science', 'Informatik', 431),
('business_informatics', 'Business Informatics', 'Wirtschaftsinformatik', 431),
('technical_informatics', 'Technical Informatics', 'technischen Informatik', 431),
('bio_and_medical_informatics', 'Bio- And Medical Informatics', 'Bio- und Medizininformatik', 431),
('geospatial', 'Geospatial', 'Geoinformatik', 431),
('media_informatics', 'Media Informatics', 'Medieninformatik', 431),
('it_system_analysis', 'It System Analysis', 'IT-Systemanalyse', 432),
('it_application_consulting', 'It Application Consulting', 'IT-Anwendungsberatung', 432),
('it_sales', 'It Sales', 'IT-Vertrieb', 432),
('it_system_analysis_it_application_consulting_and_it_sales', 'It System Analysis, It Application Consulting And It Sales', 'IT-Systemanalyse, IT-Anwendungsberatung und IT-Vertrieb', 432),
('it_network_technology', 'It Network Technology', 'IT-Netzwerktechnik', 433),
('it_coordination', 'It Coordination', 'IT-Koordination', 433),
('it_organization', 'It Organization', 'IT-Organisation', 433),
('it_system_administration', 'It System Administration', 'IT-Systemadministation', 433),
('database_development_and_administration', 'Database Development And Administration', 'Datenbankentwicklung und -administration', 433),
('web_administration', 'Web Administration', 'Webadministration', 433),
('it_network_technology_it_coordination_it_administration_and_it_organization', 'It Network Technology, It Coordination, It Administration And It Organization', 'IT-Netzwerktechnik, IT-Koordination, IT-Administration und IT-Organisation', 433),
('software_development', 'Software Development', 'Softwareentwicklung', 434),
('programming', 'Programming', 'Programmierung', 434),
('software_development_and_programming', 'Software Development And Programming', 'Softwareentwicklung und Programmierung', 434),
('technical_railway_operations', 'Technical Railway Operations', 'technischen Eisenbahnbetrieb', 511),
('technical_air_traffic_operation', 'Technical Air Traffic Operation', 'technischen Luftverkehrsbetrieb', 511),
('technical_shipping_operation', 'Technical Shipping Operation', 'technischen Schiffsverkehrsbetrieb', 511),
('correctional_service', 'Correctional Service', 'Justizvollzugsdienst', 532),
('engraving', 'Engraving', 'Gravur', 935),
('technical_operation_of_rail_air_and_ship_traffic', 'Technical Operation Of Rail, Air And Ship Traffic', 'technischen Betrieb des Eisenbahn-, Luft- und Schiffsverkehrs', 511),
('technical_operation_in_rail_air_and_ship_traffic', 'Technical Operation In Rail, Air And Ship Traffic', 'Technischer Betrieb im Eisenbahn-, Luft- und Schiffsverkehr', 511),
('road_and_tunnel_keepers', 'Road And Tunnel Keepers', 'Straßen- und Tunnelwärter/innen', 512),
('monitoring_and_maintenance_of_the_railway_infrastructure', 'Monitoring And Maintenance Of The Railway Infrastructure', 'Überwachung und Wartung der Eisenbahninfrastruktur', 512),
('air_traffic_control_technology', 'Air Traffic Control Technology', 'Flugsicherungstechnik', 512),
('waterway_and_bridge_keepers', 'Waterway And Bridge Keepers', 'Wasserstraßen- und Brückenwärter/innen', 512),
('monitoring_and_maintenance_of_the_transport_infrastructure', 'Monitoring And Maintenance Of The Transport Infrastructure', 'Überwachung und Wartung der Verkehrsinfrastruktur', 512),
('warehouse_management', 'Warehouse Management', 'Lagerwirtschaft', 513),
('professions_for_postal_and_delivery_services', 'Professions For Postal And Delivery Services', 'Berufe für Post- und Zustelldienste', 513),
('handling_of_goods_and_goods', 'Handling Of Goods And Goods', 'Güter- und Warenumschlag', 513),
('warehousing_mail_and_delivery_cargo_handling', 'Warehousing, Mail And Delivery, Cargo Handling', 'Lagerwirtschaft, Post und Zustellung, Güterumschlag', 513),
('service_staff_in_passenger_transport', 'Service Staff In Passenger Transport', 'Servicekräfte im Personenverkehr', 514),
('service_specialists_in_road_and_rail_transport', 'Service Specialists In Road And Rail Transport', 'Servicefachkräfte im Straßen- und Schienenverkehr', 514),
('service_specialists_in_aviation', 'Service Specialists In Aviation', 'Servicefachkräfte im Luftverkehr', 514),
('service_specialists_in_shipping', 'Service Specialists In Shipping', 'Servicefachkräfte im Schiffsverkehr', 514),
('passenger_traffic_service_area', 'Passenger Traffic (Service Area)', 'Personenverkehr (Servicebereich)', 514),
('monitoring_and_control_of_traffic_operations', 'Monitoring And Control Of Traffic Operations', 'Überwachung und Steuerung des Verkehrsbetriebs', 515),
('monitoring_and_control_of_road_traffic_operations', 'Monitoring And Control Of Road Traffic Operations', 'Überwachung und Steuerung des Straßenverkehrsbetriebs', 515),
('monitoring_and_control_of_rail_traffic_operations', 'Monitoring And Control Of Rail Traffic Operations', 'Überwachung und Steuerung des Eisenbahnverkehrsbetriebs', 515),
('monitoring_and_control_of_air_traffic_operations', 'Monitoring And Control Of Air Traffic Operations', 'Überwachung und Steuerung des Luftverkehrsbetriebs', 515),
('monitoring_and_control_of_ship_traffic_operations', 'Monitoring And Control Of Ship Traffic Operations', 'Überwachung und Steuerung des Schiffsverkehrsbetriebs', 515),
('transport_clerks', 'Transport Clerks', 'Verkehrskaufleute', 516),
('forwarding_and_logistics_clerks', 'Forwarding And Logistics Clerks', 'Speditions- und Logistikkaufleute', 516),
('road_and_rail_transport_clerks', 'Road And Rail Transport Clerks', 'Straßen- und Schienenverkehrskaufleute', 516),
('aviation_salesmen', 'Aviation Salesmen', 'Luftverkehrskaufleute', 516),
('shipping_merchants', 'Shipping Merchants', 'Schifffahrtskaufleute', 516),
('courier_express_and_postal_service_merchants', 'Courier, Express And Postal Service Merchants', 'Kurier-, Express- und Postdienstleistungskaufleute', 516),
('transport_and_logistics_commercial_area', 'Transport And Logistics (Commercial Area)', 'Verkehr und Logistik (kaufmännischer Bereich)', 516),
('professional_drivers_passenger_transport_cars', 'Professional Drivers (Passenger Transport / Cars)', 'Berufskraftfahrer/innen (Personentransport/PKW)', 521),
('professional_drivers_freight_transport_trucks', 'Professional Drivers (Freight Transport / Trucks)', 'Berufskraftfahrer/innen (Güterverkehr/LKW)', 521),
('bus_and_tram_drivers', 'Bus And Tram Drivers', 'Bus- und Straßenbahnfahrer/innen', 521),
('vehicle_drivers_in_road_traffic', 'Vehicle Drivers In Road Traffic', 'Fahrzeugführer/innen im Straßenverkehr', 521),
('train_drivers_in_rail_traffic', 'Train Drivers In Rail Traffic', 'Triebfahrzeugführer/innen im Eisenbahnverkehr', 522),
('pilots_and_air_traffic_controllers', 'Pilots And Air Traffic Controllers', 'Piloten/Pilotinnen und Verkehrsflugzeugführer/innen', 523),
('vehicle_drivers_in_air_traffic', 'Vehicle Drivers In Air Traffic', 'Fahrzeugführer/innen im Flugverkehr', 523),
('nautical_officers_and_masters', 'Nautical Officers And Masters', 'Nautische Schiffsoffiziere/-offizierinnen und Kapitäne/Kapitäninnen', 524),
('skippers_in_inland_navigation_and_port_traffic', 'Skippers In Inland Navigation And Port Traffic', 'Schiffsführer/innen in Binnenschifffahrt und Hafenverkehr', 524),
('operators_of_agricultural_and_forestry_machines', 'Operators Of Agricultural And Forestry Machines', 'Führer/innen von land- und forstwirtschaftlichen Maschinen', 525),
('earthmoving_and_related_machinery_operators', 'Earthmoving And Related Machinery Operators', 'Führer/innen von Erdbewegungs- und verwandten Maschinen', 525),
('crane_operators_elevator_machinists_and_operators_of_related_lifting_equipment', 'Crane Operators, Elevator Machinists And Operators Of Related Lifting Equipment', 'Kranführer/innen, Aufzugsmaschinisten und Bediener/innen verwandter Hebeeinrichtungen', 525),
('construction_and_transport_equipment_management', 'Construction And Transport Equipment Management', 'Bau- und Transportgeräteführung', 525),
('property_value_and_personal_protection', 'Property, Value And Personal Protection', 'Objekt-, Werte- und Personenschutz', 531),
('occupations_in_occupational_safety_and_security_technology', 'Occupations In Occupational Safety And Security Technology', 'Berufe in Arbeitssicherheit und Sicherheitstechnik', 531),
('fire_protection', 'Fire Protection', 'Brandschutz', 531),
('lifeguards', 'Lifeguards', 'Badeaufsicht', 531),
('detectives', 'Detectives', 'Detektive/Detektivinnen', 531),
('debt_collection_agent', 'Debt Collection Agent', 'Inkassobeauftragte', 531),
('professions_in_property_personal_fire_protection_occupational_safety', 'Professions In Property, Personal, Fire Protection, Occupational Safety', 'Berufe in Objekt-, Personen-, Brandschutz, Arbeitssicherheit', 531),
('property_personal_fire_protection_occupational_safety', 'Property, Personal, Fire Protection, Occupational Safety', 'Objekt-, Personen-, Brandschutz, Arbeitssicherheit', 531),
('law_enforcement_service', 'Law Enforcement Service', 'Polizeivollzugsdienst', 532),
('criminal_service', 'Criminal Service', 'Kriminaldienst', 532),
('judicial_enforcement', 'Judicial Enforcement', 'Gerichtsvollzug', 532),
('trade_inspection', 'Trade Inspection', 'Gewerbeaufsicht', 533),
('health_oversight_and_hygiene_monitoring', 'Health Oversight And Hygiene Monitoring', 'Gesundheitsaufsicht und Hygieneüberwachung', 533),
('food_inspection', 'Food Inspection', 'Lebensmittelkontrolle', 533),
('disinfection_and_pest_control', 'Disinfection And Pest Control', 'Desinfektion und Schädlingsbekämpfung', 533),
('trade_and_health_supervision_disinfection', 'Trade And Health Supervision, Disinfection', 'Gewerbe- und Gesundheitsaufsicht, Desinfektion', 533),
('cleaning', 'Cleaning', 'Reinigung', 541),
('building_cleaning', 'Building Cleaning', 'Gebäudereinigung', 541),
('glass_and_window_cleaning', 'Glass And Window Cleaning', 'Glas- und Fensterreinigung', 541),
('dry_cleaning', 'Dry Cleaning', 'Textilreinigung', 541),
('machine_and_plant_cleaning', 'Machine And Plant Cleaning', 'Maschinen- und Anlagenreinigung', 541),
('vehicle_cleaning', 'Vehicle Cleaning', 'Fahrzeugreinigung', 541),
('purchasing', 'Purchasing', 'Einkauf', 611),
('sales_except_information_and_communication_technologies', 'Sales (Except Information And Communication Technologies)', 'Vertrieb (außer Informations- und Kommunikationstechnologien)', 611),
('trade_brokers_and_auctioneers', 'Trade Brokers And Auctioneers', 'Handelsmakler/innen und Auktionatoren/Auktionatorinnen', 611),
('merchants_in_the_vending_machine_service', 'Merchants In The Vending Machine Service', 'Kaufleute im Automatenservice', 611),
('money_and_deposit_lending', 'Money And Deposit Lending', 'Geld- und Pfandverleih', 611),
('lending_except_money_and_deposit_lending', 'Lending (Except Money And Deposit Lending)', 'Verleih (außer Geld- und Pfandverleih)', 611),
('purchasing_and_sales', 'Purchasing And Sales', 'Einkauf und Vertrieb', 611),
('merchants_in_trade', 'Merchants In Trade', 'Kaufleute im Handel', 612),
('wholesale_and_foreign_trade_merchants', 'Wholesale And Foreign Trade Merchants', 'Kaufleute im Groß- und Außenhandel', 612),
('trade', 'Trade', 'Handel', 612),
('real_estate_marketing_and_management', 'Real Estate Marketing And Management', 'Immobilienvermarktung und -verwaltung', 613),
('facility_management', 'Facility Management', 'Facility-Management', 613),
('real_estate_industry_and_facility_management', 'Real Estate Industry And Facility Management', 'Immobilienwirtschaft und Facility-Management', 613),
('sales_without_product_specialization', 'Sales (Without Product Specialization)', 'Verkauf (ohne Produktspezialisierung)', 621),
('cashiers_and_ticket_sellers', 'Cashiers And Ticket Sellers', 'Kassierer/innen und Kartenverkäufer/innen', 621),
('sales_booths_and_market_sellers', 'Sales Booths And Market Sellers', 'Verkaufsstand- und Marktverkäufer/innen', 621),
('sale', 'Sale', 'Verkauf', 621),
('sales_of_clothing_sporting_goods_leather_goods_and_shoes', 'Sales Of Clothing, Sporting Goods, Leather Goods And Shoes', 'Verkauf von Bekleidung, Sportartikeln, Lederwaren und Schuhen', 622),
('sales_of_jewelry_and_watches', 'Sales Of Jewelry And Watches', 'Verkauf von Schmuck und Uhren', 622),
('sales_of_office_supplies_gifts_and_toys', 'Sales Of Office Supplies, Gifts And Toys', 'Verkauf von Bürobedarf, Geschenk- und Spielwaren', 622),
('sales_of_electrical_electronic_and_household_goods', 'Sales Of Electrical, Electronic And Household Goods', 'Verkauf von Elektro-, Elektronik- und Haushaltswaren', 622),
('sale_of_furniture_and_furnishings', 'Sale Of Furniture And Furnishings', 'Verkauf von Möbeln und Einrichtungsgegenständen', 622),
('sale_of_garden_do_it_yourself_pet_and_zoo_supplies', 'Sale Of Garden, Do-It-Yourself, Pet And Zoo Supplies', 'Verkauf von Garten-, Heimwerker-, Haustier- und Zoobedarf', 622),
('sales_of_automobiles_two_wheelers_and_accessories', 'Sales Of Automobiles, Two-Wheelers And Accessories', 'Verkauf von Kraftfahrzeugen, Zweirädern und Zubehör', 622),
('sale_of_groceries', 'Sale Of Groceries', 'Verkauf von Lebensmitteln', 623),
('sale_of_bakery_and_confectionery', 'Sale Of Bakery And Confectionery', 'Verkauf von Back- und Konditoreiwaren', 623),
('sale_of_meat_products', 'Sale Of Meat Products', 'Verkauf von Fleischwaren', 623),
('sale_of_common_drugstore_and_pharmacy_goods', 'Sale Of Common Drugstore And Pharmacy Goods', 'Verkauf von drogerie- und apothekenüblichen Waren', 624),
('sale_of_sanitary_and_medical_supplies', 'Sale Of Sanitary And Medical Supplies', 'Verkauf von Sanitäts- und Medizinbedarf', 624),
('book_trade', 'Book Trade', 'Buchhandel', 625),
('art_and_antiques_trade', 'Art And Antiques Trade', 'Kunst- und Antiquitätenhandel', 625),
('music_retailers', 'Music Retailers', 'Musikfachhandel', 625),
('tourism_merchants', 'Tourism Merchants', 'Tourismuskaufleute', 631),
('sports_and_fitness_salespeople_sports_managers', 'Sports And Fitness Salespeople, Sports Managers', 'Sport- und Fitnesskaufleute, Sportmanager/innen', 631),
('animators_and_guest_advisors', 'Animators And Guest Advisors', 'Animateure/Animateurinnen und Gästebetreuer/innen', 631),
('tour_guides_and_tour_guides', 'Tour Guides And Tour Guides', 'Reiseleiter/innen und Fremdenführer/innen', 631),
('tourism_and_sport', 'Tourism And Sport', 'Tourismus und Sport', 631),
('hotel_clerks', 'Hotel Clerks', 'Hotelkaufleute', 632),
('hotel_service', 'Hotel Service', 'Hotelservice', 632),
('hotel_industry', 'Hotel Industry', 'Hotellerie', 632),
('catering_service', 'Catering Service', 'Gastronomieservice', 633),
('system_catering', 'System Catering', 'Systemgastronomie', 633),
('bartenders', 'Bartenders', 'Barkeeper/innen', 633),
('gastronomy', 'Gastronomy', 'Gastronomie', 633),
('gastronomy_and_system_catering', 'Gastronomy And System Catering', 'Gastronomie und Systemgastronomie', 633),
('event_service_and_management', 'Event Service And Management', 'Veranstaltungsservice und -management', 634),
('managing_directors_and_board_members', 'Managing Directors And Board Members', 'Geschäftsführer/innen und Vorstände', 711),
('legislators', 'Legislators', 'Angehörige gesetzgebender Körperschaften', 712),
('senior_staff_of_interest_groups', 'Senior Staff Of Interest Groups', 'Leitende Bedienstete von Interessenorganisationen', 712),
('internal_electoral_offices', 'Internal Electoral Offices', 'Betriebsinterne Wahlämter', 712),
('commercial_and_technical_business_administration', 'Commercial And Technical Business Administration', 'kaufmännischen und technischen Betriebswirtschaft', 713),
('business_organization_and_planning', 'Business Organization And Planning', 'Unternehmensorganisation und -planung', 713),
('business_consulting', 'Business Consulting', 'Unternehmensberatung', 713),
('business_promotion', 'Business Promotion', 'Wirtschaftsförderung', 713),
('company_organization_and_strategy', 'Company Organization And Strategy', 'Unternehmensorganisation und -strategie', 713),
('office_and_secretarial_staff', 'Office And Secretarial Staff', 'Büro- und Sekretariatskräfte', 714),
('foreign_language_secretaries_and_foreign_language_correspondents', 'Foreign Language Secretaries And Foreign Language Correspondents', 'Fremdsprachensekretäre/-sekretärinnen und Fremdsprachenkorrespondenten/-korrespondentinnen', 714),
('interpreters_and_translators', 'Interpreters And Translators', 'Dolmetscher/innen und Übersetzer/innen', 714),
('shorthand_typists_and_phonographers', 'Shorthand Typists And Phonographers', 'Steno- und Phonotypisten/-typistinnen', 714),
('coders_proofreaders_and_related_office_workers', 'Coders, Proofreaders And Related Office Workers', 'Kodierer/innen, Korrekturleser/innen und verwandte Bürokräfte', 714),
('information_and_customer_information', 'Information And Customer Information', 'Auskunft und Kundeninformation', 714),
('office_and_secretariat', 'Office And Secretariat', 'Büro und Sekretariat', 714),
('personnel_development_and_processing', 'Personnel Development And Processing', 'Personalentwicklung und -sachbearbeitung', 715),
('personnel_services', 'Personnel Services', 'Personaldienstleistung', 715),
('human_resources_and_services', 'Human Resources And Services', 'Personalwesen und -dienstleistung', 715),
('bankers', 'Bankers', 'Bankkaufleute', 721),
('investment_advisors_and_other_financial_services_professions', 'Investment Advisors And Other Financial Services Professions', 'Anlageberater/innen und sonstige Finanzdienstleistungsberufe', 721),
('insurance_salesmen', 'Insurance Salesmen', 'Versicherungskaufleute', 721),
('financial_analysts', 'Financial Analysts', 'Finanzanalysten/-analystinnen', 721),
('insurance_and_financial_services_professions', 'Insurance And Financial Services Professions', 'Berufe in Versicherungs- und Finanzdienstleistungen', 721),
('insurance_and_financial_services', 'Insurance And Financial Services', 'Versicherungs- und Finanzdienstleistungen', 721),
('accounting', 'Accounting', 'Buchhaltung', 722),
('professions_in_cost_accounting_and_calculation', 'Professions In Cost Accounting And Calculation', 'Berufe in Kostenrechnung und Kalkulation', 722),
('controlling', 'Controlling', 'Controlling', 722),
('auditing_professions', 'Auditing Professions', 'Berufe in Wirtschaftsprüfung', 722),
('accounting_controlling_and_auditing', 'Accounting, Controlling And Auditing', 'Rechnungswesen, Controlling und Revision', 722),
('tax_advice', 'Tax Advice', 'Steuerberatung', 723),
('professions_in_legal_advice_law_and_regulation', 'Professions In Legal Advice, Law And Regulation', 'Berufe in Rechtsberatung, -sprechung und -ordnung', 731),
('assistants_in_law_firms_and_notaries', 'Assistants In Law Firms And Notaries', 'Assistenzkräfte in Rechtsanwaltskanzlei und Notariat', 731),
('notaries', 'Notaries', 'Notare/Notarinnen', 731),
('lawyers', 'Lawyers', 'Rechtsanwälte/-anwältinnen', 731),
('public_prosecutors', 'Public Prosecutors', 'Staatsanwälte/-anwältinnen', 731),
('judges', 'Judges', 'Richter/innen', 731),
('defense_of_constitution', 'Defense Of Constitution', 'Verfassungsschutz', 731),
('legal_advice_law_and_regulation', 'Legal Advice, Law And Regulation', 'Rechtsberatung, -sprechung und -ordnung', 731),
('public_administration', 'Public Administration', 'öffentlichen Verwaltung', 732),
('social_administration_and_insurance', 'Social Administration And Insurance', 'Sozialverwaltung und -versicherung', 732),
('administrative_social_and_health_care', 'Administrative Social And Health Care', 'Verwaltende Sozial- und Gesundheitswesen', 732),
('tax_administration', 'Tax Administration', 'Steuerverwaltung', 732),
('customs_service', 'Customs Service', 'Zolldienst', 732),
('judicial_administration', 'Judicial Administration', 'Justizverwaltung', 732),
('administration', 'Administration', 'Verwaltung', 732),
('archiving', 'Archiving', 'Archivwesen', 733),
('librarianship', 'Librarianship', 'Bibliothekswesen', 733),
('documentation_and_information_service', 'Documentation And Information Service', 'Dokumentations- und Informationsdienst', 733),
('medical_documentation', 'Medical Documentation', 'medizinischen Dokumentation', 733),
('media_documentation_and_information_services', 'Media, Documentation And Information Services', 'Medien-, Dokumentations- und Informationsdienste', 733),
('medical_assistant', 'Medical Assistant', 'Medizinische Fachangestellte', 811),
('dental_assistant', 'Dental Assistant', 'Zahnmedizinische Fachangestellte', 811),
('orthoptists', 'Orthoptists', 'Orthoptisten/Orthoptistinnen', 811),
('animal_medical_assistant', 'Animal Medical Assistant', 'Tiermedizinische Fachangestellte', 811),
('medical_technical_laboratory', 'Medical-Technical Laboratory', 'Medizinisch-technische Laboratorium', 812),
('medical_technical_functional_diagnostics', 'Medical-Technical Functional Diagnostics', 'Medizinisch-technische Funktionsdiagnostik', 812),
('medical_technical_radiology', 'Medical-Technical Radiology', 'Medizinisch-technische Radiologie', 812),
('medical_technical_veterinary_medicine', 'Medical-Technical Veterinary Medicine', 'Medizinisch-technische Veterinärmedizin', 812),
('medical_laboratory', 'Medical Laboratory', 'Medizinisches Laboratorium', 812),
('health_and_nursing', 'Health And Nursing', 'Gesundheits- und Krankenpflege', 813),
('specialized_nursing', 'Specialized Nursing', 'Fachkrankenpflege', 813),
('specialized_child_nursing', 'Specialized Child Nursing', 'Fachkinderkrankenpflege', 813),
('surgical_medical_assistance', 'Surgical / Medical Assistance', 'operations-/medizintechnischen Assistenz', 813),
('ambulance_service', 'Ambulance Service', 'Rettungsdienst', 813),
('obstetrics_and_childbirth_care', 'Obstetrics And Childbirth Care', 'Geburtshilfe und Entbindungspflege', 813),
('health_and_nursing_ambulance_and_obstetrics', 'Health And Nursing, Ambulance And Obstetrics', 'Gesundheits- und Krankenpflege, Rettungsdienst und Geburtshilfe', 813),
('doctors', 'Doctors', 'Ärzte/Ärztinnen', 814),
('specialists_in_pediatric_and_adolescent_medicine', 'Specialists In Pediatric And Adolescent Medicine', 'Fachärzte/-ärztinnen in der Kinder- und Jugendmedizin', 814),
('specialists_in_internal_medicine', 'Specialists In Internal Medicine', 'Fachärzte/-ärztinnen in der Inneren Medizin', 814),
('specialists_in_surgery', 'Specialists In Surgery', 'Fachärzte/-ärztinnen in der Chirurgie', 814),
('specialists_in_the_fields_of_skin_diseases_sensory_and_genital_organs', 'Specialists In The Fields Of Skin Diseases, Sensory And Genital Organs', 'Fachärzte/-ärztinnen in den Bereichen Hautkrankheiten, Sinnes- und Geschlechtsorgane', 814),
('specialists_in_anesthesiology', 'Specialists In Anesthesiology', 'Fachärzte/-ärztinnen in der Anästhesiologie', 814),
('specialists_in_neurology_psychiatry_psychotherapy_and_psychosomatic_medicine', 'Specialists In Neurology, Psychiatry, Psychotherapy And Psychosomatic Medicine', 'Fachärzte/-ärztinnen in der Neurologie, Psychiatrie, Psychotherapie und psychosomatischen Medizin', 814),
('dentists_and_orthodontists', 'Dentists And Orthodontists', 'Zahnärzte/-ärztinnen und Kieferorthopäden/-orthopädinnen', 814),
('human_medicine_and_dentistry', 'Human Medicine And Dentistry', 'Human- und Zahnmedizin', 814),
('veterinarians', 'Veterinarians', 'Tierärzte/-ärztinnen', 815),
('veterinarians_for_large_and_farm_animals', 'Veterinarians For Large And Farm Animals', 'Tierärzte/-ärztinnen für Groß- und Nutztiere', 815),
('veterinarians_for_pets_and_pets', 'Veterinarians For Pets And Pets', 'Tierärzte/-ärztinnen für Haus- und Heimtiere', 815),
('animal_healers', 'Animal Healers', 'Tierheilpraktiker/innen', 815),
('veterinary_medicine_and_veterinary_medicine', 'Veterinary Medicine And Veterinary Medicine', 'Tiermedizin und Tierheilkunde', 815),
('not_clinical_psychology', 'Not Clinical Psychology', 'nicht klinischen Psychologie', 816),
('clinical_psychology', 'Clinical Psychology', 'klinischen Psychologie', 816),
('not_medical_psychotherapy', 'Not Medical Psychotherapy', 'nicht ärztlichen Psychotherapie', 816),
('physical_therapy', 'Physical Therapy', 'Physiotherapie', 817),
('occupational_therapy', 'Occupational Therapy', 'Ergotherapie', 817),
('speech_therapy', 'Speech Therapy', 'Sprachtherapie', 817),
('music_and_art_therapy', 'Music And Art Therapy', 'Musik- und Kunsttherapie', 817),
('medicine_and_homeopathy', 'Medicine And Homeopathy', 'Heilkunde und Homöopathie', 817),
('diet_and_nutritional_therapy', 'Diet And Nutritional Therapy', 'Diät- und Ernährungstherapie', 817),
('podologists', 'Podologists', 'Podologen/Podologinnen', 817),
('not_medical_therapy_and_medicine', 'Not Medical Therapy And Medicine', 'nicht ärztlichen Therapie und Heilkunde', 817),
('not_medical_therapy_and_medicine', 'Not Medical Therapy And Medicine', 'Nicht ärztliche Therapie und Heilkunde', 817),
('pharmacists_pharmacists', 'Pharmacists, Pharmacists', 'Apotheker/innen, Pharmazeuten/Pharmazeutinnen', 818),
('specialists_in_pharmacology', 'Specialists In Pharmacology', 'Fachärzte/-ärztinnen in der Pharmakologie', 818),
('pharmaceutical_technical_assistance', 'Pharmaceutical-Technical Assistance', 'pharmazeutisch-technischen Assistenz', 818),
('pharmacy', 'Pharmacy', 'Pharmazie', 818),
('elderly_care', 'Elderly Care', 'Altenpflege', 821),
('health_advice', 'Health Advice', 'Gesundheitsberatung', 822),
('wellness_professions', 'Wellness Professions', 'Wellnessberufe', 822),
('nutritional_advice', 'Nutritional Advice', 'Ernährungsberatung', 822),
('quality_officer_in_health_care', 'Quality Officer In Health Care', 'Qualitätsbeauftragte im Gesundheitswesen', 822),
('professions_in_nutrition_and_health_advice_wellness', 'Professions In Nutrition And Health Advice, Wellness', 'Berufe in Ernährungs- und Gesundheitsberatung, Wellness', 822),
('hairdressing', 'Hairdressing', 'Friseurgewerbe', 823),
('cosmetics', 'Cosmetics', 'Kosmetik', 823),
('tattoo_artists_and_piercers', 'Tattoo Artists And Piercers', 'Tätowierer/innen und Piercer/innen', 823),
('makeup_art', 'Makeup Art', 'Maskenbildnerei', 823),
('personal_hygiene', 'Personal Hygiene', 'Körperpflege', 823),
('funeral_services', 'Funeral Services', 'Bestattungswesen', 824),
('medical_technology', 'Medical Technology', 'Medizintechnik', 825),
('orthopedic_and_rehabilitation_technology', 'Orthopedic And Rehabilitation Technology', 'Orthopädie- und Rehatechnik', 825),
('optics', 'Optics', 'Augenoptik', 825),
('hearing_aid_acoustics', 'Hearing Aid Acoustics', 'Hörgeräteakustik', 825),
('dental_technology', 'Dental Technology', 'Zahntechnik', 825),
('medical_orthopedic_and_rehabilitation_technology', 'Medical, Orthopedic And Rehabilitation Technology', 'Medizin-, Orthopädie- und Rehatechnik', 825),
('child_care_and_education', 'Child Care And Education', 'Kinderbetreuung und -erziehung', 831),
('social_work_and_social_pedagogy', 'Social Work And Social Pedagogy', 'Sozialarbeit und Sozialpädagogik', 831),
('professions_in_curative_care_and_special_education', 'Professions In Curative Care And Special Education', 'Berufe in Heilerziehungspflege und Sonderpädagogik', 831),
('home_and_family_care', 'Home And Family Care', 'Haus- und Familienpflege', 831),
('social_educational_and_addiction_counseling', 'Social, Educational And Addiction Counseling', 'Sozial-, Erziehungs- und Suchtberatung', 831),
('education_social_work_curative_education_care', 'Education, Social Work, Curative Education Care', 'Erziehung, Sozialarbeit, Heilerziehungspflege', 831),
('housekeeping', 'Housekeeping', 'Hauswirtschaft', 832),
('consumer_advice', 'Consumer Advice', 'Verbraucherberatung', 832),
('housekeeping_and_consumer_advice', 'Housekeeping And Consumer Advice', 'Hauswirtschaft und Verbraucherberatung', 832),
('theology', 'Theology', 'Theologie', 833),
('church_work', 'Church Work', 'Gemeindearbeit', 833),
('members_of_religious_orders_and_mother_houses', 'Members Of Religious Orders And Mother Houses', 'Angehörige geistlicher Orden und Mutterhäuser', 833),
('theology_and_church_work', 'Theology And Church Work', 'Theologie und Gemeindearbeit', 833),
('teachers_at_primary_level', 'Teachers At Primary Level', 'Lehrkräfte in der Primarstufe', 841),
('secondary_school_teachers', 'Secondary School Teachers', 'Lehrkräfte in der Sekundarstufe', 841),
('teachers_at_special_schools', 'Teachers At Special Schools', 'Lehrkräfte an Förderschulen', 841),
('teacher_training', 'Teacher Training', 'Lehrerausbildung', 841),
('teachers_in_general_education_schools', 'Teachers In General Education Schools', 'Lehrkräfte an allgemeinbildenden Schulen', 841),
('general_education_schools', 'General Education Schools', 'Allgemeinbildende Schulen', 841),
('teachers_for_vocational_subjects', 'Teachers For Vocational Subjects', 'Lehrkräfte für berufsbildende Fächer', 842),
('in_company_training_and_in_company_pedagogy', 'In-Company Training And In-Company Pedagogy', 'betrieblichen Ausbildung und Betriebspädagogik', 842),
('vocational_schools_in_company_training_and_in_company_pedagogy', 'Vocational Schools, In-Company Training And In-Company Pedagogy', 'Berufsschulen, betriebliche Ausbildung und Betriebspädagogik', 842),
('university_teaching_and_research', 'University Teaching And Research', 'Hochschullehre und -forschung', 843),
('adult_education', 'Adult Education', 'Erwachsenenbildung', 844),
('music_education', 'Music Education', 'Musikpädagogik', 844),
('religious_education', 'Religious Education', 'Religionspädagogik', 844),
('art_and_theater_education', 'Art And Theater Education', 'Kunst- und Theaterpädagogik', 844),
('it_application_training', 'It Application Training', 'IT-Anwendungstraining', 844),
('_foreign_language_teachers', '(Foreign) Language Teachers', '(Fremd-)Sprachenlehrer/innen', 844),
('teachers_at_extracurricular_educational_institutions', 'Teachers At Extracurricular Educational Institutions', 'Lehrkräfte an außerschulischen Bildungseinrichtungen', 844),
('extracurricular_educational_institutions', 'Extracurricular Educational Institutions', 'Außerschulische Bildungseinrichtungen', 844),
('pe_teachers', 'Pe Teachers', 'Sportlehrer/innen', 845),
('driving_instructors', 'Driving Instructors', 'Fahrlehrer/innen', 845),
('flight_instructors', 'Flight Instructors', 'Fluglehrer/innen', 845),
('dance_teachers', 'Dance Teachers', 'Tanzlehrer/innen', 845),
('trainers_ball_sports', 'Trainers - Ball Sports', 'Trainer/innen - Ballsportarten', 845),
('trainers_fitness_and_gymnastics', 'Trainers - Fitness And Gymnastics', 'Trainer/innen - Fitness und Gymnastik', 845),
('professions_in_linguistics_and_literary_studies', 'Professions In Linguistics And Literary Studies', 'Berufe in Sprach- und Literaturwissenschaften', 911),
('german_studies', 'German Studies', 'Germanistik', 911),
('english_and_american_studies', 'English And American Studies', 'Anglistik und Amerikanistik', 911),
('romance_studies', 'Romance Studies', 'Romanistik', 911),
('slavic_studies_and_related_fields', 'Slavic Studies And Related Fields', 'Slawistik und verwandten Bereichen', 911),
('arabic_and_oriental_studies', 'Arabic And Oriental Studies', 'Arabistik und Orientalistik', 911),
('professions_in_linguistics_and_literary_studies_in_the_asian_region', 'Professions In Linguistics And Literary Studies In The Asian Region', 'Berufe in Sprach- und Literaturwissenschaften des asiatischen Raums', 911),
('classical_philology', 'Classical Philology', 'Altphilologie', 911),
('professions_in_philosophy_religion_and_ethics', 'Professions In Philosophy, Religion And Ethics', 'Berufe in Philosophie, Religion und Ethik', 912),
('professions_in_history', 'Professions In History', 'Berufe in Geschichtswissenschaften', 912),
('archeology', 'Archeology', 'Archäologie', 912),
('professions_in_media_and_theater_studies', 'Professions In Media And Theater Studies', 'Berufe in Medien- und Theaterwissenschaft', 912),
('regional_science', 'Regional Science', 'Regionalwissenschaft', 912),
('anthropology_and_ethnology', 'Anthropology And Ethnology', 'Anthropologie und Ethnologie', 912),
('political_science', 'Political Science', 'Politologie', 913),
('sociology', 'Sociology', 'Soziologie', 913),
('pedagogy', 'Pedagogy', 'Erziehungswissenschaft', 913),
('market_and_opinion_research', 'Market And Opinion Research', 'Markt- und Meinungsforschung', 913),
('demographics', 'Demographics', 'Demografie', 913),
('occupations_in_social_sciences', 'Occupations In Social Sciences', 'Berufe in Gesellschaftswissenschaften', 913),
('professions_in_economics', 'Professions In Economics', 'Berufe in Wirtschaftswissenschaften', 914),
('professions_in_advertising_and_marketing', 'Professions In Advertising And Marketing', 'Berufe in Werbung und Marketing', 921),
('dialogue_marketing', 'Dialogue Marketing', 'Dialogmarketing', 921),
('customer_management', 'Customer Management', 'Kundenmanagement', 921),
('advertising_and_marketing', 'Advertising And Marketing', 'Werbung und Marketing', 921),
('public_relation', 'Public Relation', 'Öffentlichkeitsarbeit', 922),
('publishing_and_media_clerks', 'Publishing And Media Clerks', 'Verlags- und Medienkaufleute', 923),
('publishing_and_media_industry', 'Publishing And Media Industry', 'Verlags- und Medienwirtschaft', 923),
('editors_and_journalists', 'Editors And Journalists', 'Redakteure/Redakteurinnen und Journalisten/Journalistinnen', 924),
('lecturers', 'Lecturers', 'Lektoren/Lektorinnen', 924),
('authors', 'Authors', 'Autoren/Autorinnen und Schriftsteller/innen', 924),
('editing_and_journalism', 'Editing And Journalism', 'Redaktion und Journalismus', 924),
('product_and_industrial_design', 'Product And Industrial Design', 'Produkt- und Industriedesign', 931),
('interior_design', 'Interior Design', 'Innenarchitektur', 932),
('visual_marketing', 'Visual Marketing', 'visuellen Marketing', 932),
('interior_equipment', 'Interior Equipment', 'Raumausstattung', 932),
('interior_design_visual_marketing_interior_design', 'Interior Design, Visual Marketing, Interior Design', 'Innenarchitektur, visuelles Marketing, Raumausstattung', 932),
('crafts_and_fine_arts_professions', 'Crafts And Fine Arts Professions', 'Berufe in Kunsthandwerk und bildender Kunst', 933),
('sculpture', 'Sculpture', 'Bildhauerei', 933),
('artists_and_draftsmen', 'Artists And Draftsmen', 'Kunstmaler/innen und Zeichner/innen', 933),
('wood_turning_and_toy_manufacturing', 'Wood Turning And Toy Manufacturing', 'Drechslerei und Spielzeugherstellung', 933),
('gilding_craft', 'Gilding Craft', 'Vergolderhandwerk', 933),
('wax_drawing', 'Wax Drawing', 'Wachszieherei', 933),
('crafts_and_fine_arts', 'Crafts And Fine Arts', 'Kunsthandwerk und bildende Kunst', 933),
('handicraft_ceramic_design', 'Handicraft Ceramic Design', 'kunsthandwerklichen Keramikgestaltung', 934),
('artisanal_glass_ceramic_and_porcelain_painting', 'Artisanal Glass, Ceramic And Porcelain Painting', 'kunsthandwerklichen Glas-, Keram- und Porzellanmalerei', 934),
('artisanal_glass_blowing', 'Artisanal Glass Blowing', 'kunsthandwerklichen Glasbläserei', 934),
('artisanal_ceramic_and_glass_design', 'Artisanal Ceramic And Glass Design', 'Kunsthandwerkliche Keramik- und Glasgestaltung', 934),
('craft_metal_design', 'Craft Metal Design', 'kunsthandwerklichen Metallgestaltung', 935),
('handicraft_jewelry_making_precious_stone_and_precious_metal_processing', 'Handicraft Jewelry Making, Precious Stone And Precious Metal Processing', 'kunsthandwerklichen Schmuckwarenherstellung, Edelstein- und Edelmetallbearbeitung', 935),
('sign_and_light_advertising_production', 'Sign And Light Advertising Production', 'Schilder- und Lichtreklameherstellung', 935),
('artisanal_metal_design', 'Artisanal Metal Design', 'Kunsthandwerkliche Metallgestaltung', 935),
('musical_instrument_making', 'Musical Instrument Making', 'Musikinstrumentenbau', 936),
('string_and_plucked_instrument_making', 'String And Plucked Instrument Making', 'Streich- und Zupfinstrumentenbau', 936),
('woodwind_instrument_making', 'Woodwind Instrument Making', 'Holzblasinstrumentenbau', 936),
('brass_instrument_making', 'Brass Instrument Making', 'Metallblasinstrumentenbau', 936),
('piano_and_harpsichord_construction', 'Piano And Harpsichord Construction', 'Klavier- und Cembalobau', 936),
('organ_and_harmonium_building', 'Organ And Harmonium Building', 'Orgel- und Harmoniumbau', 936),
('musicians', 'Musicians', 'Musiker/innen', 941),
('singers', 'Singers', 'Sänger/innen', 941),
('conductors', 'Conductors', 'Dirigenten/Dirigentinnen', 941),
('composers', 'Composers', 'Komponisten/Komponistinnen', 941),
('music_singing_and_conducting_activities', 'Music, Singing And Conducting Activities', 'Musik-, Gesangs- und Dirigententätigkeiten', 941),
('actors', 'Actors', 'Schauspieler/innen', 942),
('dancers_and_choreographers', 'Dancers And Choreographers', 'Tänzer/innen und Choreografen/Choreografinnen', 942),
('mannequins_dressmen_and_other_models', 'Mannequins, Dressmen And Other Models', 'Mannequins, Dressmen und sonstige Models', 942),
('athletes_and_professional_athletes', 'Athletes And Professional Athletes', 'Athleten/Athletinnen und Berufssportler/innen', 942),
('professions_for_personal_services', 'Professions For Personal Services', 'Berufe für personenbezogene Dienstleistungen', 942),
('professions_in_acting_dance_and_movement_arts', 'Professions In Acting, Dance And Movement Arts', 'Berufe in Schauspiel, Tanz und Bewegungskunst', 942),
('professions_in_moderation_and_entertainment', 'Professions In Moderation And Entertainment', 'Berufe in Moderation und Unterhaltung', 943),
('comedians_and_cabaret_artists', 'Comedians And Cabaret Artists', 'Komiker/innen und Kabarettisten/Kabarettistinnen', 943),
('sorcerers_and_illusionists', 'Sorcerers And Illusionists', 'Zauberer/Zauberinnen und Illusionisten/Illusionistinnen', 943),
('radio_and_television_presenters', 'Radio And Television Presenters', 'Hörfunk- und Fernsehmoderatoren/-moderatorinnen', 943),
('gambling_and_betting_area', 'Gambling And Betting Area', 'Bereich Glücks- und Wettspiel', 943),
('theater_film_and_television_production', 'Theater, Film And Television Production', 'Theater-, Film- und Fernsehproduktion', 944),
('director', 'Director', 'Regie', 944),
('event_and_stage_technology', 'Event And Stage Technology', 'Veranstaltungs- und Bühnentechnik', 945),
('camera_technology', 'Camera Technology', 'Kameratechnik', 945),
('image_and_sound_technology', 'Image And Sound Technology', 'Bild- und Tontechnik', 945),
('event_camera_and_sound_technology', 'Event, Camera And Sound Technology', 'Veranstaltungs-, Kamera- und Tontechnik', 945),
('stage_and_costume_design', 'Stage And Costume Design', 'Bühnen- und Kostümbildnerei', 946),
('prop', 'Prop', 'Requisite', 946),
('stage_and_costume_design_props', 'Stage And Costume Design, Props', 'Bühnen- und Kostümbildnerei, Requisite', 946),
('museum_professions', 'Museum Professions', 'Museumsberufe', 947),
('museum_and_exhibition_technology', 'Museum And Exhibition Technology', 'Museums- und Ausstellungstechnik', 947),
('art_appraisers', 'Art Appraisers', 'Kunstsachverständige', 947),
('museum', 'Museum', 'Museum', 947),
('officers', 'Officers', 'Offiziere', 11),
('ncos_with_portepee', 'NCOs With Portepee', 'Unteroffiziere mit Portepee', 12),
('ncos_without_portepee', 'NCOs Without Portepee', 'Unteroffiziere ohne Portepee', 13),
('members_of_the_regular_armed_forces_in_other_ranks', 'Members Of The Regular Armed Forces In Other Ranks', 'Angehörige der regulären Streitkräfte in sonstigen Rängen', 14);
`

class ProfessionSchema extends Schema {
  up() {
    this.create('professions', (table) => {
      table.increments()
      table.string('value', 120)
      table.string('title_en', 120)
      table.string('title_de', 120)
      table.integer('type').unsigned()
    })

    this.schedule(async (trx) => {
      await Database.raw(sql).transacting(trx)
    })
  }

  down() {
    this.drop('professions')
  }
}

module.exports = ProfessionSchema
