name: Breeze Backend Development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: development
      # Enable once build commands are created
      # - name: Install Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '12.x'
      # - name: Install npm dependencies
      #   run: npm install --force
      # - name: Run build task
      #   run: npm run build --if-present
      - name: Sync to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY_DEV }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: './'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_DEV }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_DEV }}
          TARGET: /home/ubuntu/source/core
          EXCLUDE: '/.github/'
      - name: executing build command remotely
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST_DEV }}
          username: ${{ secrets.REMOTE_USER_DEV }}
          key: ${{ secrets.SERVER_SSH_KEY_DEV }}
          script_stop: true
          # Below are test commands to verify integration
          script: |
            cd /home/ubuntu/source/core
            ./trigger-build.sh -e dev
